### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by matteopompei** [mifi/SimpleInstaBot#103]
He can't even log in :/ 

```
7:47 PMNo cookies found
7:47 PMSetting language to English (en)
7:47 PMWaiting 1 sec
7:47 PMWaiting 3 sec
7:47 PMFound language selector
7:47 PMSelected language
7:47 PMWaiting 4 sec
7:47 PMWaiting 2 sec
7:47 PMLogin page button not found, assuming we have login form
7:47 PMWaiting 1 sec
7:47 PMWaiting 2 sec
7:47 PMFailed to run TypeError: Cannot read property 'click' of undefined
```

**Comment by mifi** [comment]
could yoiu take a screenshot of the page right after you got this error?

**Comment by matteopompei** [comment]
I have to manually click to continue logging in
![Immagine 2021-12-09 100928](https://user-images.githubusercontent.com/3842462/145378658-a4d0f06d-8466-49b1-b3c6-a1d68ab24e66.png)

**Comment by matteopompei** [comment]
On Ubuntu it looks like it doesn't even load the page

![image](https://user-images.githubusercontent.com/3842462/145649462-723313d1-852e-4853-a594-d540c440b3e4.png)

**Comment by mifi** [comment]
that's odd. seems like the bot is failing to change language to english. are you able to manually change language to english (the bot only works on english)

**Comment by mifi** [comment]
Hard to say. could you see if there are any errors in the command line, or try to open developer tools in the white window and see if anything shows up?

**Comment by mifi** [comment]
I have now made some improvements that will hopefully fix this
