### ISSUE TITLE
Failed to process follower (follower name) Error: Follow button not found

### ISSUE THREAD

**Issue by madroots** [mifi/SimpleInstaBot#106]
Hello, above error is suddenly taking place, no new follow is made. Follow button not found?  

Acc is fine, I can follow manually or using another script however SimpleInstaBot just keep skipping users with the Error above. 

can you help please? Thanks!

**Comment by mifi** [comment]
nice if you could provide some more info, like screenshots and error messages

**Comment by madroots** [comment]
Thank you for quick reply. Here is screenshot: 
https://ctrlv.link/shots/2022/02/09/y5Ii.png


config:
{
  "maxFollowsPerDay": 80,
  "maxFollowsPerHour": 10,
  "maxLikesPerDay": 25,
  "maxLikesPerUser": 2,
  "followUserRatioMin": 0.2,
  "followUserRatioMax": 4,
  "followUserMaxFollowers": null,
  "followUserMaxFollowing": null,
  "followUserMinFollowers": null,
  "followUserMinFollowing": 10,
  "dontUnfollowUntilDaysElapsed": 2,
  "runAtHour": 9
}

Also, I will say step by step:
1. Bot starts fine, logs into IG account, navigate to profile
2. Bot unable to follow, prints error Follow button not found
3. Bot navigates to another profile and tries to follow, however it cant, end up with same error
4. This will loop again and again. It was working fine yesterday, suddenly this happens

Facts:
1. I tested this with multiple PC's (2x Linux and 1x Windows)
2. I tried with multiple IG accounts
3. I am not blocked, suspended etc - I can follow anyone manually
4. I can even click follow button directly inside bot window
5. Yesterday it was working fine


Thank you so much for your help.

**Comment by mifi** [comment]
somewhat related #79

**Comment by mifi** [comment]
thanks. i also experienced the same issue. seems like instagram changed the follow button html structure. I have now fixed that so will release a new version

**Comment by mifi** [comment]
@Cyberavater maybe. If you could create a new issue and follow the instructions to include html, that would be very helpful
