### ISSUE TITLE
Has more pages going on "forever" when following many thousand accounts

### ISSUE THREAD

**Issue by mifi** [mifi/SimpleInstaBot#108]
Hi, 
Thank you for making this great tool.
I have just installed it recently on my Win10, version SimpleInstaBot 1.8.3
I see the same error after starting the Bot, I can see it logs into Instagram ok, but after awhile, it start showing codes. Below is the print screen and the log, could you please advise what's the problem, Thank you so much :)

![image](https://user-images.githubusercontent.com/99350173/153246062-61dcc044-8b53-415d-bccb-d2612ee7cfb8.png)

LOGS FROM LAST RUN
12:32 AMSetting language to English (en)
12:32 AMWaiting 2 sec
12:32 AMWaiting 5 sec
12:32 AMFound language selector
12:32 AMSelected language
12:32 AMWaiting 4 sec
12:32 AMWaiting 1 sec
12:32 AMSaving cookies
12:32 AMHave followed/unfollowed 0 in the last hour
12:32 AMHave followed/unfollowed 0 in the last 24 hours
12:32 AMHave liked 0 images in the last 24 hours
12:32 AMUnfollowing currently followed users who were auto-followed more than 5 days ago...
12:32 AMNavigating to user kgtechwear
12:32 AMGoto https://www.instagram.com/kgtechwear
12:32 AMWaiting 2 sec
12:32 AMHas more pages (current 1)
12:32 AMHas more pages (current 2)
12:32 AMHas more pages (current 3)
12:32 AMHas more pages (current 4)
12:32 AMHas more pages (current 5)
12:32 AMHas more pages (current 6)
12:32 AMHas more pages (current 7)
12:32 AMHas more pages (current 8)
12:32 AMHas more pages (current 9)
12:32 AMHas more pages (current 10)
12:32 AMHas more pages (current 11)
12:32 AMError: Navigation failed because browser has disconnected!
12:32 AMSleeping 9.899703572431637 hours (waiting until 10:00)...

_Originally posted by @friendlyG in https://github.com/mifi/SimpleInstaBot/issues/101#issuecomment-1033958298_

**Comment by friendlyG** [comment]
oh yes, I see that the Bot is tried to refresh the login screen 3 times until it enters the username and password, is that why?

As you've said, I let it run longer and finally I see the proper Instagram screen, no more codes, Yeah.

But a new error appears. 
1:27 AMFailed to process follower miles_wilson.ffl Error: Follow button not found

I let it runs a bit longer, and it seems that it's happening to all IG accounts that it is trying to follow, please see attached screen shot and the log. Thank you so much.

![image](https://user-images.githubusercontent.com/99350173/153721739-0beaacae-6a58-4c49-96bf-8d4aece6ee38.png)


LOGS FROM LAST RUN
1:19 AMNo cookies found
1:19 AMSetting language to English (en)
1:19 AMWaiting 2 sec
1:19 AMWaiting 5 sec
1:20 AMFound language selector
1:20 AMSelected language
1:20 AMWaiting 3 sec
1:20 AMWaiting 2 sec
1:20 AMLogin page button not found, assuming we have login form
1:20 AMWaiting 2 sec
1:20 AMWaiting 1 sec
1:20 AMWaiting 11 sec
1:20 AMSetting language to English (en)
1:20 AMWaiting 2 sec
1:20 AMWaiting 3 sec
1:20 AMFound language selector
1:20 AMSelected language
1:20 AMWaiting 6 sec
1:20 AMWaiting 2 sec
1:20 AMSaving cookies
1:20 AMHave followed/unfollowed 0 in the last hour
1:20 AMHave followed/unfollowed 0 in the last 24 hours
1:20 AMHave liked 2 images in the last 24 hours
1:20 AMUnfollowing currently followed users who were auto-followed more than 5 days ago...
1:20 AMNavigating to user kgtechwear
1:20 AMGoto https://www.instagram.com/kgtechwear
1:20 AMWaiting 2 sec
1:20 AMHas more pages (current 1)
1:20 AMHas more pages (current 2)
1:20 AMHas more pages (current 3)
1:20 AMHas more pages (current 4)
1:20 AMHas more pages (current 5)
1:20 AMHas more pages (current 6)
1:20 AMHas more pages (current 7)
1:20 AMHas more pages (current 8)
1:20 AMHas more pages (current 9)
1:20 AMHas more pages (current 10)
1:20 AMHas more pages (current 11)
1:20 AMHas more pages (current 12)
1:21 AMHas more pages (current 13)
1:21 AMHas more pages (current 14)
1:21 AMHas more pages (current 15)
1:21 AMHas more pages (current 16)
1:21 AMHas more pages (current 17)
1:21 AMHas more pages (current 18)
1:21 AMHas more pages (current 19)
1:21 AMHas more pages (current 20)
1:21 AMHas more pages (current 21)
1:21 AMHas more pages (current 22)
1:21 AMHas more pages (current 23)
1:21 AMHas more pages (current 24)
1:21 AMHas more pages (current 25)
1:21 AMHas more pages (current 26)
1:21 AMHas more pages (current 27)
1:21 AMHas more pages (current 28)
1:21 AMHas more pages (current 29)
1:21 AMHas more pages (current 30)
1:21 AMHas more pages (current 31)
1:21 AMHas more pages (current 32)
1:21 AMHas more pages (current 33)
1:21 AMHas more pages (current 34)
1:21 AMHas more pages (current 35)
1:21 AMHas more pages (current 36)
1:21 AMHas more pages (current 37)
1:21 AMHas more pages (current 38)
1:21 AMHas more pages (current 39)
1:21 AMHas more pages (current 40)
1:21 AMHas more pages (current 41)
1:21 AMHas more pages (current 42)
1:21 AMHas more pages (current 43)
1:21 AMHas more pages (current 44)
1:21 AMHas more pages (current 45)
1:21 AMHas more pages (current 46)
1:21 AMHas more pages (current 47)
1:21 AMHas more pages (current 48)
1:21 AMHas more pages (current 49)
1:21 AMHas more pages (current 50)
1:21 AMHas more pages (current 51)
1:21 AMHas more pages (current 52)
1:21 AMHas more pages (current 53)
1:21 AMHas more pages (current 54)
1:21 AMHas more pages (current 55)
1:21 AMHas more pages (current 56)
1:21 AMHas more pages (current 57)
1:21 AMHas more pages (current 58)
1:21 AMHas more pages (current 59)
1:21 AMHas more pages (current 60)
1:21 AMHas more pages (current 61)
1:21 AMHas more pages (current 62)
1:21 AMHas more pages (current 63)
1:21 AMHas more pages (current 64)
1:21 AMHas more pages (current 65)
1:21 AMHas more pages (current 66)
1:21 AMHas more pages (current 67)
1:21 AMHas more pages (current 68)
1:21 AMHas more pages (current 69)
1:21 AMHas more pages (current 70)
1:21 AMHas more pages (current 71)
1:21 AMHas more pages (current 72)
1:21 AMHas more pages (current 73)
1:21 AMHas more pages (current 74)
1:21 AMHas more pages (current 75)
1:21 AMHas more pages (current 76)
1:21 AMHas more pages (current 77)
1:21 AMHas more pages (current 78)
1:21 AMHas more pages (current 79)
1:21 AMHas more pages (current 80)
1:21 AMHas more pages (current 81)
1:21 AMHas more pages (current 82)
1:21 AMHas more pages (current 83)
1:21 AMHas more pages (current 84)
1:21 AMHas more pages (current 85)
1:21 AMHas more pages (current 86)
1:21 AMHas more pages (current 87)
1:21 AMHas more pages (current 88)
1:21 AMHas more pages (current 89)
1:21 AMHas more pages (current 90)
1:21 AMHas more pages (current 91)
1:21 AMHas more pages (current 92)
1:21 AMHas more pages (current 93)
1:21 AMHas more pages (current 94)
1:21 AMHas more pages (current 95)
1:21 AMHas more pages (current 96)
1:21 AMHas more pages (current 97)
1:21 AMHas more pages (current 98)
1:21 AMHas more pages (current 99)
1:22 AMHas more pages (current 100)
1:22 AMHas more pages (current 101)
1:22 AMHas more pages (current 102)
1:22 AMHas more pages (current 103)
1:22 AMHas more pages (current 104)
1:22 AMHas more pages (current 105)
1:22 AMHas more pages (current 106)
1:22 AMHas more pages (current 107)
1:22 AMHas more pages (current 108)
1:22 AMHas more pages (current 109)
1:22 AMHas more pages (current 110)
1:22 AMHas more pages (current 111)
1:22 AMHas more pages (current 112)
1:22 AMHas more pages (current 113)
1:22 AMHas more pages (current 114)
1:22 AMHas more pages (current 115)
1:22 AMHas more pages (current 116)
1:22 AMHas more pages (current 117)
1:22 AMHas more pages (current 118)
1:22 AMHas more pages (current 119)
1:22 AMHas more pages (current 120)
1:22 AMHas more pages (current 121)
1:22 AMHas more pages (current 122)
1:22 AMHas more pages (current 123)
1:22 AMHas more pages (current 124)
1:22 AMHas more pages (current 125)
1:22 AMHas more pages (current 126)
1:22 AMHas more pages (current 127)
1:22 AMHas more pages (current 128)
1:22 AMHas more pages (current 129)
1:22 AMHas more pages (current 130)
1:22 AMHas more pages (current 131)
1:22 AMHas more pages (current 132)
1:22 AMHas more pages (current 133)
1:22 AMHas more pages (current 134)
1:22 AMHas more pages (current 135)
1:22 AMHas more pages (current 136)
1:22 AMHas more pages (current 137)
1:22 AMHas more pages (current 138)
1:22 AMHas more pages (current 139)
1:22 AMHas more pages (current 140)
1:22 AMHas more pages (current 141)
1:22 AMHas more pages (current 142)
1:22 AMHas more pages (current 143)
1:22 AMHas more pages (current 144)
1:22 AMHas more pages (current 145)
1:22 AMHas more pages (current 146)
1:22 AMHas more pages (current 147)
1:22 AMHas more pages (current 148)
1:22 AMHas more pages (current 149)
1:22 AMHas more pages (current 150)
1:22 AMHas more pages (current 151)
1:22 AMHas more pages (current 152)
1:22 AMHas more pages (current 153)
1:22 AMusersToUnfollow []
1:22 AMUnfollowing 0 users
1:22 AMFollowing up to 151 followers of jay_carillo
1:22 AMNavigating to user jay_carillo
1:22 AMGoto https://www.instagram.com/jay_carillo
1:22 AMWaiting 2 sec
1:22 AMHas more pages (current 1)
1:22 AMHas more pages (current 2)
1:22 AMHas more pages (current 3)
1:22 AMFollowers phoenixtrinityfirearms,rexxpedition,beverlyelizabeth12345,nik_ki2231,son_of_tactics,abc.firearmstactics,nitismeofficial,madisongrace2022,alphatbsolutions_llc,jamie_audrey255,the_tylerashley,mikehwang,miles_wilson.ffl,levelup_live_official,defensesyztems,andrewdenino,dax_cade,davidwarren4599,jason_b_3gun,theguncamp,jessicafxanna1,nelsonjd1977,chris_spores1,yamila06_fx,sixmts5,tonyacevedoc,just_battles87,anna_scotland_fx,kmichaelmunday,survivalgearbso,alfred._.elon,golden.waterfowl.outfitters,_aaronfajardo32,mmpi_llc,caps_278,jsteel2137,stroup.knives,khaledm8q8,maria_ghent,isotunessport,wreed618,sethjprice,youngwolf6.5,horizon_tactics,wylieee_,antoniofx5487624,sievershenry,texaspatriot1311,salisu.adamu.ismail,jasonmiller4r,david_fitzstephens,beth.any7827,equilibriumfirearms_,shootarillusion,harleygirl_3gun,linda_rose096,wish.comdilleneasley,weaver_guns,johnsonsmith2642,kelly____moore______2638,itzasuamaley,long_gfx,madnessandanarchy,bullets380,patchpartay,_quentindefense,iwigasgunchallenge,kentkuykendall,wisconsinairgunners,firearms_international_llc,notoriousfde,gidefense,scott_tactical9198,w_t_frank,house_of_ammunitionz,julianna_avani,margaret_anthony843,indierecordentlabel4o3587,vinnie_jay_2,ddahl5570,_mustafaaceylann,scott_shoots_it_all,alxemcl,claiph40,mark.morgan5860,alesos3,precisionhunter55,shirleybarter01,monicaparris0992,dean.bradley72,jeremynmoore,kitngun,hecatonak,isaac_cadle76,joh_nson1578,mokambejunior,plugr_usa,aloha.assassin,jpdamo,shellbackoc9,jimlong1384,twista_guncoach,fiasco_team,yousmartfirearmsllc,mycustomgun,carrollnd22,eyesonjamie,waisaipapa,ky.hayworth,nobleknifedesign,g.allan.ping,breacherscustoms,cci_ammunitions,naterbomb,thirdworldmedic,juliana.mary4,dakotaadventuress,limitedmajor,look_an_asian,openshooter94,mellenthin_c_00,aggressive_cyberbot,gerault.c,americandefensetarheelchalleng,lea.nnacox,xtreme_guns_and_ammo,dennis_smithback,josiaholmstead_3gun,survivor4575,git_some1110,joshiepewpew14,losangeles_cs_company,jud4du,3gunjoshua,mjmkodrich,3gunthor,ltothep123,et_3gun,0lightworld,gbltblat,dynamic_target_systems,gregsgruns,ridingjosh,mcdaniel.philip,jyost.shooting,andrey_ipsc,brentjohn__,gmdex24,the_guns_store013,brand_ammo_,eclipseholsters,dlapresi,rotary.break,alfredourquijo,hc843,thesupreme_edgelord_666,anlise450,chigunslingers,akadian3gun,freddie_leonard_091,zechcope,asaafirearmstraining,davedaplumber,mamapolarbear007,kornykidd0,armeriabullkillerstore,chempionka10,exotics.indoors,toyota_camry_officials,c_a_coating
1:22 AMNavigating to user phoenixtrinityfirearms
1:22 AMGoto https://www.instagram.com/phoenixtrinityfirearms
1:22 AMWaiting 1 sec
1:23 AMUser has too many followers compared to follows or opposite, skipping
1:23 AMNavigating to user rexxpedition
1:23 AMGoto https://www.instagram.com/rexxpedition
1:23 AMWaiting 1 sec
1:23 AMUser has too many followers compared to follows or opposite, skipping
1:23 AMNavigating to user beverlyelizabeth12345
1:23 AMGoto https://www.instagram.com/beverlyelizabeth12345
1:23 AMWaiting 1 sec
1:23 AMUser is private, skipping
1:23 AMNavigating to user nik_ki2231
1:23 AMGoto https://www.instagram.com/nik_ki2231
1:23 AMWaiting 1 sec
1:23 AMUser has too many followers compared to follows or opposite, skipping
1:23 AMNavigating to user son_of_tactics
1:23 AMGoto https://www.instagram.com/son_of_tactics
1:23 AMWaiting 2 sec
1:23 AMFailed to process follower son_of_tactics Error: Follow button not found
1:23 AMWaiting 34 sec
1:23 AMNavigating to user abc.firearmstactics
1:23 AMGoto https://www.instagram.com/abc.firearmstactics
1:23 AMWaiting 2 sec
1:23 AMUser has too many followers compared to follows or opposite, skipping
1:23 AMNavigating to user nitismeofficial
1:23 AMGoto https://www.instagram.com/nitismeofficial
1:24 AMWaiting 2 sec
1:24 AMFailed to process follower nitismeofficial Error: Follow button not found
1:24 AMWaiting 28 sec
1:24 AMNavigating to user madisongrace2022
1:24 AMGoto https://www.instagram.com/madisongrace2022
1:24 AMWaiting 1 sec
1:24 AMUser is private, skipping
1:24 AMNavigating to user alphatbsolutions_llc
1:24 AMGoto https://www.instagram.com/alphatbsolutions_llc
1:24 AMWaiting 1 sec
1:24 AMFailed to process follower alphatbsolutions_llc Error: Follow button not found
1:24 AMWaiting 35 sec
1:25 AMNavigating to user jamie_audrey255
1:25 AMGoto https://www.instagram.com/jamie_audrey255
1:25 AMWaiting 2 sec
1:25 AMUser is private, skipping
1:25 AMNavigating to user the_tylerashley
1:25 AMGoto https://www.instagram.com/the_tylerashley
1:25 AMWaiting 1 sec
1:25 AMFailed to process follower the_tylerashley Error: Follow button not found
1:25 AMWaiting 30 sec
1:25 AMNavigating to user mikehwang
1:25 AMGoto https://www.instagram.com/mikehwang
1:25 AMWaiting 2 sec
1:25 AMWe are already following this user
1:25 AMWaiting 6 sec
1:26 AMWaiting 10 sec
1:26 AMLiking 1-2 user images
1:26 AMWaiting 4 sec
1:26 AMWaiting 4 sec
1:26 AMWaiting 5 sec
1:26 AMWaiting 6 sec
1:26 AMWaiting 3 sec
1:26 AMWaiting 10 sec
1:26 AMWaiting 35 sec
1:27 AMNavigating to user miles_wilson.ffl
1:27 AMGoto https://www.instagram.com/miles_wilson.ffl
1:27 AMWaiting 1 sec
1:27 AMFailed to process follower miles_wilson.ffl Error: Follow button not found
1:27 AMWaiting 34 sec
1:27 AMNavigating to user levelup_live_official
1:27 AMGoto https://www.instagram.com/levelup_live_official
1:28 AMWaiting 2 sec
1:28 AMUser has too many followers compared to follows or opposite, skipping
1:28 AMNavigating to user defensesyztems
1:28 AMGoto https://www.instagram.com/defensesyztems
1:28 AMWaiting 1 sec
1:28 AMUser has too many followers compared to follows or opposite, skipping
1:28 AMNavigating to user andrewdenino
1:28 AMGoto https://www.instagram.com/andrewdenino
1:28 AMWaiting 2 sec
1:28 AMWe are already following this user
1:28 AMWaiting 6 sec
1:28 AMWaiting 13 sec
1:28 AMLiking 1-2 user images
1:28 AMWaiting 6 sec
1:28 AMWaiting 4 sec
1:28 AMWaiting 5 sec
1:29 AMWaiting 30 sec
1:29 AMNavigating to user dax_cade
1:29 AMGoto https://www.instagram.com/dax_cade
1:29 AMWaiting 2 sec
1:29 AMUser has too many followers compared to follows or opposite, skipping
1:29 AMNavigating to user davidwarren4599
1:29 AMGoto https://www.instagram.com/davidwarren4599
1:29 AMWaiting 1 sec
1:29 AMUser is private, skipping
1:29 AMNavigating to user jason_b_3gun
1:29 AMGoto https://www.instagram.com/jason_b_3gun
1:29 AMWaiting 2 sec
1:29 AMFailed to process follower jason_b_3gun Error: Follow button not found
1:29 AMWaiting 26 sec
1:30 AMNavigating to user theguncamp
1:30 AMGoto https://www.instagram.com/theguncamp
1:30 AMWaiting 2 sec
1:30 AMUser has too many followers compared to follows or opposite, skipping
1:30 AMNavigating to user jessicafxanna1
1:30 AMGoto https://www.instagram.com/jessicafxanna1
1:30 AMWaiting 1 sec
1:30 AMUser is private, skipping
1:30 AMNavigating to user nelsonjd1977
1:30 AMGoto https://www.instagram.com/nelsonjd1977
1:30 AMWaiting 1 sec
1:30 AMFailed to process follower nelsonjd1977 Error: Follow button not found
1:30 AMWaiting 28 sec
1:31 AMNavigating to user chris_spores1
1:31 AMGoto https://www.instagram.com/chris_spores1
1:31 AMWaiting 2 sec
1:31 AMFailed to process follower chris_spores1 Error: Follow button not found
1:31 AMWaiting 31 sec

**Comment by mifi** [comment]
I think it's due to this bug #106 - please upgrade to 1.8.4

**Comment by mifi** [comment]
this has been improved now in the next version
