### ISSUE TITLE
stop bot and lose logs

### ISSUE THREAD

**Issue by rohsshor** [mifi/SimpleInstaBot#115]
Hello, why if I stop the bot I lose the logs?
in fact, i have to unfollow people manually

Rohs 
![Catturaaa](https://user-images.githubusercontent.com/35661106/156587675-e31c8ee6-eed3-49c0-99b5-f881e8e5a2d3.JPG)

**Comment by mifi** [comment]
the bot will only lose the text logs. It will still save the users that have been followed, and will later unfollow them, don't worry

**Comment by mifi** [comment]
ok i just changed the text in that dialog to: `This will terminate the bot and you will lose any log text. Note that the bot will still remember which users it has followed, and will unfollow them in the future.`

**Comment by rohsshor** [comment]
> ok i just changed the text in that dialog to: `This will terminate the bot and you will lose any log text. Note that the bot will still remember which users it has followed, and will unfollow them in the future.`

Ok, thank you for you reply. I have understand :)
Just an information, could I unfollow all the people that I follow with your bot withou follow new people?

**Comment by mifi** [comment]
maybe if you set the number of people to follow to 0 but i havent tried
