### ISSUE TITLE
sometimes it says "Button did not change state - Sleeping"

### ISSUE THREAD

**Issue by xkenkanekiii** [mifi/SimpleInstaBot#121]
Sometimes bot says "button did not change state - sleeping" even the bot works properly. After that the bot waits random seconds then "Failed to process follower ------ Error: Button did not change state" is appears.

I don't know why, could you help me?

Thanks

**Comment by mifi** [comment]
Hi. if you could take a screenshot of the browser window at the time it happens, that would be helpful. probably instagram is blocking the action or something like that

**Comment by xkenkanekiii** [comment]
<img width="577" alt="Ekran Resmi 2022-03-28 22 57 32" src="https://user-images.githubusercontent.com/84245269/160476981-edb3c054-d0dc-4b16-b2e4-6473ac292de6.png">

its like that

**Comment by mifi** [comment]
I mean the other window, the instagram page, how does it look like?

**Comment by mifi** [comment]
can you see if it's fixed with the newest version?

**Comment by davidereitano** [comment]
also with latest version, same issue. This only happens when following private profiles

**Comment by mifi** [comment]
I think this issue has been resolved now. try the latest version 1.10.5

**Comment by niklasof** [comment]
hi @mifi :)
Unfortunately, I just encountered the same issue even with the latest version (1.11.1), see screenshot. Any ideas what could be the issue here? It seems that it works for the first around 10ish profiles and then get stuck in that error 🤔
![Screenshot 2022-09-21 at 14 20 55](https://user-images.githubusercontent.com/19303209/191502653-eb746f6d-3a3c-4333-9a6a-6e864a9a9597.png)

**Comment by mifi** [comment]
could be a bug in instagram too, or the button press getting blocked by instagram, thereby nothing happening. hard to say without knowing which network requests were sent

**Comment by niklasof** [comment]
> 

I see. Any chance you'll find the time to look into this soon or any further input I can help provide here? That would be awesome :)

**Comment by mifi** [comment]
if you can provide the network request/response happening after the button has been pressed, it would be helpful (using devtools)

**Comment by ediooo** [comment]
I am getting the same thing here.
