### ISSUE TITLE
Bot follows random people not inside config.json

### ISSUE THREAD

**Issue by sinfulz** [mifi/SimpleInstaBot#122]
The bot is following random people. I checked a random person inside the config.json file and its not there? Any ideas what's going on?

**Comment by mifi** [comment]
I don't understand. The bot does not store which person it follows inside config.json
See https://github.com/mifi/SimpleInstaBot/blob/master/public/store.js

**Comment by sinfulz** [comment]
1. I put ~300 followers in the list to follow (List of accounts followers to follow)
2. It starts following users not in that list
3. In app data on Windows there’s a config.json which shows those users from step 1. (C:\Users\sinfulz\AppData\Roaming\SimpleInstaBot\config.json)

**Comment by sinfulz** [comment]
Sorry didn’t mean to close it.

**Comment by mifi** [comment]
if you read the description, you will see that it's not designed to follow a list of users. it is designed to follow **the followers** of the users that you specify. So I think it's working as intented

**Comment by mifi** [comment]
If you want to simply follow a list of users, then you can use https://github.com/mifi/instauto, or SimpleInstaBot could implement such a feature in the future.

**Comment by sinfulz** [comment]
Fair enough - makes sense. Cheers.

**Comment by adriangigliotti** [comment]
> If you want to simply follow a list of users, then you can use https://github.com/mifi/instauto, or SimpleInstaBot could implement such a feature in the future. See #77

Was this implemented?

**Comment by sinfulz** [comment]
> If you want to simply follow a list of users, then you can use https://github.com/mifi/instauto, or SimpleInstaBot could implement such a feature in the future. See #77

Was this implemented?

**Comment by mifi** [comment]
yes, try latest version
