### ISSUE TITLE
Bot is liking user image ONLY if the user is skipped

### ISSUE THREAD

**Issue by TakkoKlo** [mifi/SimpleInstaBot#127]
Hey there!
First of all: the bot is working just fine.
I just got one issue that is bothering me:
I would like the bot to like an image after following a specific user but the bot is only liking images of users that he wants to skip.
For example: if the user is private or the followers and follow camparison is too big, instead of just skipping them, the bot likes a photo and moves on to the next user.
If the follow was successfull the bot moves on navigating to the next user without liking an image.
I would really appreciate if the bot only likes an image of a user if the following before was successfull.

This issue appears on my raspberry pi B3+ aswell as on my windows pc.

Here's an example of the situation:

![example](https://user-images.githubusercontent.com/76124580/163973954-66c9f55c-0bae-4f76-bde2-bf902e3d9b3a.png)

Note: independent of the error message after following a user, the specific user is followed. So the following function is working fine.
But maybe the problem I explained has something to do with it.

**Comment by TakkoKlo** [comment]
This is the window of chromium on my raspberry pi 3B+:

![example2](https://user-images.githubusercontent.com/76124580/163993676-ce9f45df-8ff6-467d-a2a8-8f540c45aaf8.png)

Note: user images and description is blurred due to privacy reasons

**Comment by mifi** [comment]
ok tahnks for reporting, have fixed this

**Comment by TakkoKlo** [comment]
Now it's working like a charm!
Thanks alot for your good and fast work.
I really appreciate this. Keep going
