### ISSUE TITLE
Unfollow "Requested" profiles

### ISSUE THREAD

**Issue by c-chytoudis** [mifi/SimpleInstaBot#131]
After many days using Instagram bot I saw a list of private profiles that bot requested to follow. It's possible the bot to delete these requests with a feature like "Unfollow list" which already has but only for already following profiles? Thank you.

![image](https://user-images.githubusercontent.com/77646310/166678391-86577200-49a4-41a9-b529-57f9a51c08b9.png)

![image](https://user-images.githubusercontent.com/77646310/166678409-4b4c78af-c7cf-4978-822c-3f21d7507c4f.jpeg)

**Comment by mifi** [comment]
Hi. the bot should already unfollow these "requested" users when unfollowing. Does it not do that? if not, what error are you getting?
See relevant code here:
https://github.com/mifi/instauto/blob/49e72bab51f7f0342f055409deeb64c18306992b/src/index.js#L306

**Comment by c-chytoudis** [comment]
Hello, when bot is going to follow a private profile has this error log:

![image](https://user-images.githubusercontent.com/77646310/166903166-4c26aa55-db35-44aa-b7a9-d9e536221440.jpeg)

**When I use this "Unfollow list" action:**

![image](https://user-images.githubusercontent.com/77646310/166903268-f514e440-cd38-4c23-b14d-0c1c38402e98.png)

**I get this:**

![image](https://user-images.githubusercontent.com/77646310/166903355-4e2187e6-b614-4fcb-b273-1b4fbe62efe4.jpeg)

Bot do not unfollow requested profiles if the user does not first accept the follow request. The bot only unfollows requested profiles when user accept the request even if the user accept it after several days.

**Comment by mifi** [comment]
Ok, this is a bug then that needs to be fixed

**Comment by mifi** [comment]
can try the newest version - i did some minor improvement that might fix this

**Comment by c-chytoudis** [comment]
Hello, I tried new version 1.10.4 but the issue is still the same.

When I try **Unfollow list**:

![image](https://user-images.githubusercontent.com/77646310/172494541-76a55162-bc9d-472d-9a0f-5c1949f3dbc6.png)

I still have this error:

![image](https://user-images.githubusercontent.com/77646310/172494584-f75fe43c-b0ea-4b43-9151-bac27dc52d0c.png)

For these **Requested** profiles:

![image](https://user-images.githubusercontent.com/77646310/172494648-73be2547-0cfa-43e5-8b9e-180caf14c3d9.png)

When I was looking at **followed.json** file I found **failed:true** (I don't know if this is a feature):

![image](https://user-images.githubusercontent.com/77646310/172494843-9240fdf5-db9a-489c-ac8f-4e3f7017f03e.png)

**failed:true** happens when bot tries to follow private profiles and **Follow** button changes to **Requested** as I posted before:

![image](https://user-images.githubusercontent.com/77646310/172495076-7b34b3e9-f85e-46ba-960b-43498418a85e.jpeg)

**Comment by mifi** [comment]
Ok, I would really like to know what is the HTML content of the "Requested" button.
I think this is similar to this issue #79

Could you try to provide me the HTML of the button, like the person did here:
https://github.com/mifi/SimpleInstaBot/issues/79#issuecomment-887634044

Even better, copy (CTRL-C) and then paste the HTML here

**Comment by c-chytoudis** [comment]
**innerHTML:**
<div class="_ab8w  _ab94 _ab99 _ab9f _ab9k _ab9p"><div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9o  _abb0"><button class="_acan _acap _acat" type="button"><div class="_aacl _aaco _aacw _aad6 _aade">Requested</div></button></div></div>

**outerHTML:**
<div class="_ab8w  _ab94 _ab99 _ab9f _ab9k _ab9p  _abb3"><div class="_ab8w  _ab94 _ab99 _ab9f _ab9k _ab9p"><div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9o  _abb0"><button class="_acan _acap _acat" type="button"><div class="_aacl _aaco _aacw _aad6 _aade">Requested</div></button></div></div></div>

**Comment by mifi** [comment]
thanks for the details. I think I have now fixed this issue, will push a new version
