### ISSUE TITLE
Failed to run - Try the troubleshooting button. Error: User not found

### ISSUE THREAD

**Issue by mosokaz** [mifi/SimpleInstaBot#133]
after starting the bot, it logs in normally, goes to the "EDIT PROFILE" section and gives this error.
(ubuntu  - firefox - laptop)
![screenbug](https://user-images.githubusercontent.com/105844605/169232146-5872ae0e-d1e6-4a35-9a36-8d7211246080.png)

**Comment by mifi** [comment]
does it happen every time?

**Comment by mosokaz** [comment]
> does it happen every time?

hi,thanks , 
it happens every time but only with that account that before everything worked well but then nothing to do.. With another account everything works ok for the moment. I noticed that user password autofill does not happen, I have to enter the data manually (I do not know and this indication may serve you)

**Comment by Eagle-SK** [comment]
I confirm the error. When I choose the "Unfollow only" option, the error message "User not Found" appears.
When I choose "Start bot", the error is "Failed to run SyntaxError: Unexpected token o in JSON at position 1"

**Comment by wyarex** [comment]
> I confirm the error. When I choose the "Unfollow only" option, the error message "User not Found" appears.
When I choose "Start bot", the error is "Failed to run SyntaxError: Unexpected token o in JSON at position 1"
The login goes fine, the errors only show up when the bot enters my profile.

Same exact error is occurring for me as well.

**Comment by andinch** [comment]
With me this error appears likewise.

**Comment by Tonners15** [comment]
Any solution to this. I had it working till yesterday! and this started showing up. 

Failed to run
Try the troubleshooting button. Error:
Unexpected token o in JSON at position 1

**Comment by Tonners15** [comment]
> after starting the bot, it logs in normally, goes to the "EDIT PROFILE" section and gives this error. (ubuntu - firefox - laptop) ![screenbug](https://user-images.githubusercontent.com/105844605/169232146-5872ae0e-d1e6-4a35-9a36-8d7211246080.png)

Same on my.

**Comment by youssef456** [comment]
i have the same issue

**Comment by mifi** [comment]
see #125

**Comment by mifi** [comment]
this should now be fixed in the latest version

**Comment by youssef456** [comment]
thanks
