### ISSUE TITLE
Missing graphql in page falling back in alternative method / Failed to run SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by kukastyke** [mifi/SimpleInstaBot#139]
First of all, infinite thanks for your work, as Tony Stark says, I love you 3k.

-Prior to the error, I have not made or seen any variation or strange thing in the bot, everything like the last few months.
-When the error occurred, I updated one of the computers to the latest updated bot and the problem is the same with the updated bot and without updating.
-I have 3 computers, two with W10 and 1 with W11 that worked perfectly with 3 different accounts.

I think it was the 31st of this past month, they stopped working at the same time with the same error:
In the Window where Instagram is seen it says this:
for (;;);{"redirect":"https:\/\/www.instagram.com\/myinstaaccount\/"}

![Screenshot_mifi1](https://user-images.githubusercontent.com/64051723/171992542-d87c487b-8339-487b-97fc-e3b839d8dcae.png)

In the window of the log we can see that
![Screenshot_MIFI 3](https://user-images.githubusercontent.com/64051723/171992562-9f8e1036-d54d-4016-9659-d7a67108cbc9.png)

Failed to run
Try the troubleshooting button. Error:
Unexpected token o in JSON at position 1

 
![Screenshot_mifi2](https://user-images.githubusercontent.com/64051723/171992615-411f76d2-053a-495b-a1e4-963b1850ed90.png)

LOG:
Missing graphql in page falling back in alternative method
Failed to run SyntaxError: Unexpected token o in JSON at position 1

Did you receive an error while the bot is running?
when connecting it

**Comment by mifi** [comment]
Hi. You are running an old version of simpleinstabot (1.10.1) which no longer works. please upgrade to the newest.
