### ISSUE TITLE
Bot stops running after some time

### ISSUE THREAD

**Issue by JannikZed** [mifi/SimpleInstaBot#14]
Hi there,
Thank you for the good work here! I'm running the bot on a mac server. I realised, that the service is stopping to run soon after I'm no longer looking at the bot window. The program is opened, but it is just not doing anything any longer. When focusing the window again, it starts running again. 
It is also visible in the logs. The bot stopped operating at 9:09 the last day and when focusing the window again, it continued to run at 6:05 PM the next day.
```
9:09 PMNavigating to user mayahalteinfachdiefresse
9:09 PMSleeping 1.867665811692172 sec
9:09 PMfollowedByCount: 60 followsCount: 119
9:09 PMFollowing user mayahalteinfachdiefresse
6:05 PMSleeping 5.703788375003248 sec
6:06 PMSleeping 1.7138594745936955 sec
6:06 PMSleeping 37.26973131047808 sec
```
Do you have any idea, where this could come from?

**Comment by mifi** [comment]
does your mac sleep?

**Comment by JannikZed** [comment]
Well, the mac is a server, so it never sleeps. It does all kinds of home automation for me :D 
But I'm trying it out now. I have the feeling, that mac OS is somehow sending just the bot to sleep after some time of inactivity. I have no experience with mac os software development, so I really don't now. I'm trying out caffeinate right now.

**Comment by mifi** [comment]
So you're saying that whenever the bot window is in the background (not the active window), the bot is paused immediately? But if you leave the bot window as the active window it will keep running for hours?

**Comment by JannikZed** [comment]
no it's really strange .. after some time it just gets inactive. Right now it seems to work. I will keep you updated, when I experience something else. Closing it for now.
