### ISSUE TITLE
Failed to Run : User Not Found

### ISSUE THREAD

**Issue by NicolasMazzoleni** [mifi/SimpleInstaBot#140]
Hi there,

Been using the bot for weeks now and since two days without any particulars reasons it stopped working with this error. (Failed To Run, Try the troubleshooting button. Error: User Not Found).

So I cleared all the accounts and added only one that exists and this error still pops up. 

Would you have an idea of the reason why ?

Thanks for the great project !
Nic
<img width="555" alt="Screenshot 2022-06-06 at 4 12 31 PM" src="https://user-images.githubusercontent.com/34337703/172178795-896d1a7d-036c-4b39-97f5-e77e1385e36e.png">

**Comment by mifi** [comment]
which version are you running? please see existing recently closed issues

**Comment by davidereitano** [comment]
Same issue here with 1.10.3

**Comment by davidereitano** [comment]
This is what happens in the browser.
this happen when the bot tries to reach the profile page, in fact if I browse manually to that page I encounter the same error.
This only happens since yesterday and only on one profile.
If I use IG for that profile from my phone app, all is normal

<img width="760" alt="Schermata 2022-06-07 alle 08 42 30" src="https://user-images.githubusercontent.com/51096690/172315130-e2642c47-acf7-478d-800d-f3a863736d56.png">

**Comment by davidereitano** [comment]
<img width="340" alt="Schermata 2022-06-07 alle 10 13 40" src="https://user-images.githubusercontent.com/51096690/172330753-dfc40b81-4747-4b17-8cd4-7a23169ae179.png">

**Comment by TakkoKlo** [comment]
Hey.
I got the same issue!
When I start the bot, it is way too fast after scanning my profile.
For example: the bot wants to start and gives itself 2 seconds. Maybe my wifi is not fast enought, but my instagram page is loading after the estimated time of 2-3 seconds past. Then I receive the same problem like NicolasMazzoleni.
Maybe increasing the time to scan the profile is fixing the problem.

I got the same issue as davidereitano aswell:
When the bot tries to find a user from which he should scan the follower, he gives himself too less time (just 2 seconds). 
So the same problem occurse: the given time is not long enough for loading the profile (my assumption)..

![bot-example](https://user-images.githubusercontent.com/76124580/172471086-311efdc0-96bb-4af4-be80-56a50a94676e.png)

**Comment by NicolasMazzoleni** [comment]
Hi,

I've been updated to 10.0.5 and the problem since to be similar again. Here is a screenshot for you.
<img width="1505" alt="Screenshot 2022-06-08 at 10 22 26 PM" src="https://user-images.githubusercontent.com/34337703/172710074-ad47d962-875b-4f43-b44d-81b01a961ac5.png">

Regards,
Nico

**Comment by mifi** [comment]
@NicolasMazzoleni it seems like the error "User not found" is correct, because the user does indeed not exist ("Sorry, this page isn't available").
Does it happen for all users the bot tries to visit? and what if you try with a different instagram account? Maybe instagram has flagged your account, and that's why you're getting this error

**Comment by NicolasMazzoleni** [comment]
> @NicolasMazzoleni it seems like the error "User not found" is correct, because the user does indeed not exist ("Sorry, this page isn't available"). Does it happen for all users the bot tries to visit? and what if you try with a different instagram account? Maybe instagram has flagged your account, and that's why you're getting this error

It actually does the same on all accounts. But it was working agin on 1.10.4, but I don't have the AppImage 1.10.4 anymore. Is there a way to download it again while you find what is going on ? (And yes maybe the account has been flagged, but I'd like to try again on 1.10.4 as it was working couple days ago).

Regards,
Nico

**Comment by getitdonestudio** [comment]
> but I don't have the AppImage 1.10.4 anymore. Is there a way to download it again while you find what is going on ? (And yes maybe the account has been flagged, but I'd like to try again on 1.10.4 as it was working couple days ago).

I'm facing the same problem with 1.10.4 aswell as with 1.10.5.
@NicolasMazzoleni You can find the 1.10.4 Version here: https://github.com/mifi/SimpleInstaBot/releases/tag/v1.10.4

**Comment by mifi** [comment]
Seems like the issue gets resolved if waiting for 24hr #142

**Comment by Flamintus** [comment]
> @NicolasMazzoleni it seems like the error "User not found" is correct, because the user does indeed not exist ("Sorry, this page isn't available"). Does it happen for all users the bot tries to visit? and what if you try with a different instagram account? Maybe instagram has flagged your account, and that's why you're getting this error

Does it happen for all users the bot tries to visit?
YES
What if you try with a different instagram account? 
Working again
Maybe instagram has flagged your account, and that's why you're getting this error
For sure -> Have to wait 24h to see it working again
