### ISSUE TITLE
Save information

### ISSUE THREAD

**Issue by eduoliihezz** [mifi/SimpleInstaBot#141]
It's only a suggestion, I don't have problems with the app.
I will like that you can save info like the accounts that you follow before run the bot. The bot send lots of request, so it can be cool that with a button you start unfollowing all the accounts that you follow with the bot. I mean, If I have 345 following accounts and with the bot I follow 600 accounts, that when I click the button I have another time 345 following. I don't know if I'm explaining well

**Comment by mifi** [comment]
I'm not 100% sure what you're asking but the bot will already automatically unfollow the accounts that it followed, after X days.

**Comment by eduoliihezz** [comment]
So meaning that if I follow like 200 accounts and the bot follow 100 ( total 300 ), after X days that 100 accounts will be unfollowed ?

**Comment by mifi** [comment]
Right, that’s how the bot works. Please see the instructions
