### ISSUE TITLE
Like button section not found

### ISSUE THREAD

**Issue by muhammedaksam** [mifi/SimpleInstaBot#148]
**To Reproduce**
`{
  "maxFollowsPerDay": 150,
  "maxFollowsPerHour": 20,
  "maxLikesPerDay": 50,
  "maxLikesPerUser": 2,
  "enableFollowUnfollow": true,
  "followUserRatioMin": 0.2,
  "followUserRatioMax": 4,
  "followUserMaxFollowers": null,
  "followUserMaxFollowing": null,
  "followUserMinFollowers": null,
  "followUserMinFollowing": 10,
  "dontUnfollowUntilDaysElapsed": 5,
  "runAtHour": 10
}`
Bot was trying to like photo from random user it found. This is the 2nd time that it happened and I am pretty sure if comments are disabled for random users image, it can't locate the like button.

**Screenshots**
![Ekran görüntüsü 2022-07-13 132013](https://user-images.githubusercontent.com/27314049/178711479-58823acd-16ed-4de2-9482-2395910bb4dd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 103.0.5060.114

**Additional context**
Failed to process follower xyz Error: Evaluation failed: Error: Like button section not found at likeCurrentUserImagesPageCode (__puppeteer_evaluation_script__:38:27)

**Provide me with HTML**
I was so late to copy the HTML. But error code is above and it might be helpful. If it's not enough, I can send another HTML if I see anyone that has comments disabled.

**Comment by ediooo** [comment]
having the same issue.
