### ISSUE TITLE
Stop automatically when using unfollow-only

### ISSUE THREAD

**Issue by asafari72** [mifi/SimpleInstaBot#157]
Hi,
When I try to use the unfollow-only feature, the bot stops automatically.
I followed about 60 people using the bot and I was going to unfollow them with this option.

 - OS: Windows 10 64-bit
 - Browser: Chrome
 - App Version: 1.11.0

**The last logs before stopping the bot:** 
```
1:40 AMUnfollowing currently followed users who were auto-followed more than 5 days ago (limit undefined)...
1:40 AMUnfollowing users, up to limit undefined
1:40 AMDone with unfollowing 0 0
```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25130241/180623192-ff34b418-fc98-4926-8c16-bed8bca56180.PNG)

Thankful

**Comment by mifi** [comment]
you never said when you followed these people with the bot. was it more than 5 days before you ran the unfollow function?

**Comment by asafari72** [comment]
I followed one day and unfollowed the next day.

**Comment by mifi** [comment]
then it's working as expected, as can be seen by reading the log you quoted:
> Unfollowing currently followed users who were auto-followed more than 5 days ago
you can configure this value of 5 days
