### ISSUE TITLE
Failed to run TimeoutError: Timeout exceeded while waiting for event

### ISSUE THREAD

**Issue by teddybeaar** [mifi/SimpleInstaBot#159]
Been running this app for the past couple weeks, and recently the past couple days been receiving this error. Doesn't follow, or unfollow, just instantly gets TimeoutError. Obviously removed by IG handle with "xxxxxx"

8:16 PMNo cookies found
8:16 PMSetting language to English (en)
8:16 PMWaiting 2 sec
8:16 PMWaiting 3 sec
8:16 PMFound language selector
8:16 PMAlready English language
8:16 PMWaiting 2 sec
8:16 PMNo login page button, assuming we are on login form
8:16 PMWaiting 1 sec
8:16 PMWaiting 2 sec
8:16 PMWaiting 11 sec
8:16 PMSetting language to English (en)
8:16 PMWaiting 2 sec
8:16 PMWaiting 4 sec
8:16 PMFound language selector
8:16 PMAlready English language
8:16 PMSaving cookies
8:16 PMHave followed/unfollowed 0 in the last hour
8:16 PMHave followed/unfollowed 88 in the last 24 hours
8:16 PMHave liked 1 images in the last 24 hours
8:16 PMNavigating to user xxxxxx
8:16 PMGoto xxxxxx
8:16 PMWaiting 2 sec
8:17 PMFailed to run TimeoutError: Timeout exceeded while waiting for event

**Comment by mifi** [comment]
what do you see in the browser window?

**Comment by Radin-H** [comment]
I get a similar error, and for me what happens is that it goes to my page, highlights the username for some reason, and then times out after a bit

**Comment by ms0508** [comment]
It also happens to me in one user, in another user that I have it works fine.
very strange.
How can this be fixed?

**Comment by mifi** [comment]
I think I found the reason:

Try to set your bio (profile) on your account, to something. see if that helps

**Comment by ms0508** [comment]
Hi @mifi 
Same problem.
I try to delete all and after that to set new bio.

**Comment by mifi** [comment]
ok yea the bio solution did not work. see discussion here: https://github.com/mifi/instauto/issues/115

**Comment by ms0508** [comment]
But I use  your exe app.
Tell me what to do and I will try and update you

**Comment by mifi** [comment]
The exe uses instauto also. You can follow progress there. Will publish a new simpleinstabot version once fixed

**Comment by mifi** [comment]
you can test newest version now https://github.com/mifi/SimpleInstaBot/releases/tag/v1.11.1

**Comment by ms0508** [comment]
Thanks
I will test now

בתאריך שבת, 30 ביולי 2022, 22:33, מאת Mikael Finstad ‏<
***@***.***>:

**Comment by teddybeaar** [comment]
Everythings working so far! Thanks for the new version.
