### ISSUE TITLE
Unfollow mode

### ISSUE THREAD

**Issue by JannikZed** [mifi/SimpleInstaBot#16]
Hi there,
I was thinking, if there is an unfollow mode possible? I actually want to unfollow all of the users, that the bot started to follow. Setting the `maxfollowperday` to zero is an "invalid parameter".

**Comment by JannikZed** [comment]
Actually, it would be sufficient to add something like "max followers total"? Because right now it seems uncontrollable, how many people the bot follows in total. Right now we have like 550 more people we follow. Something like 300 would be way better for us and the bot should just unfollow users until that number is reached again.
Do you think something like that is possible?

**Comment by mifi** [comment]
the bot will only unfollow people that the bot previously followed. you asking for a function to just unfollow everything?

**Comment by JannikZed** [comment]
Actually, I would like to see something like a clean-up. So that the bot is unfollowing every user that it previously followed. Because we came across the issue, that the bot just uncontrollable started following hundreds of users and we suddenly doubled the number of accounts we follow. Something like unfollow mode would be nice to cleanup from time to time.

**Comment by mifi** [comment]
The bot automatically unfollows the users that it followed after a few days though (configurable)

https://github.com/mifi/instauto/blob/42cb5b6203d23d23bee7bc571f0581132bbf4e3c/index.js#L48

**Comment by mifi** [comment]
If you set the unfollow time to 1 day, then it should unfollow users every day

**Comment by apollotsantos** [comment]
I think he wants to have a function to unfollow all people the bot followed, kind of resetting his following list to what it was before the bot. I've done it by setting unfollow time to 1 day and entering only my username on the watchlist.

**Comment by mifi** [comment]
there is now a new mode of operation implemented in the latest version for this!
