### ISSUE TITLE
Some sort of "json at position" error log

### ISSUE THREAD

**Issue by jankrueck** [mifi/SimpleInstaBot#160]
Hey there, 

I was just wondering if this is a problem on my side or on "your" side :)
Using your product for 30 something hours after you pushed the latest patch.
It seems to work anyways, just wanted to let you know that there is something happening on a win10 client that caught my eye ;)

Thanks for your wonderful work. (also on the lottie react player)

Cheers, 

`11:18 AMSetting language to English (en)
11:18 AMWaiting 1.17 sec
11:18 AMWaiting 5.80 sec
11:18 AMFound language selector
11:18 AMAlready English language
11:18 AMWaiting 1.07 sec
11:18 AMSaving cookies
11:18 AMHave followed/unfollowed 0 in the last hour
11:18 AMHave followed/unfollowed 17 in the last 24 hours
11:18 AMHave liked 44 images in the last 24 hours
11:18 AMTrying to get user data from HTML
_11:18 AMNavigating to user xxxxxxxxxx
11:18 AMGoto https://www.instagram.com/xxxxxxxxxx_
11:19 AMPage loaded
11:19 AMWaiting 2.37 sec
**11:19 AMFailed to get user data from page SyntaxError: Unexpected token u in JSON at position 5776**
11:19 AMNeed to intercept network request to get user data
11:19 AMUnable to intercept request, will send manually
11:19 AMUnfollowing currently followed users who were auto-followed more than 5 days ago (limit 13)...
11:19 AMUnfollowing users, up to limit 13
11:19 AMHas more pages (current 1)
11:19 AMDone with unfollowing 0 0
11:19 AMFollowing up to 4 followers of acropixie
11:19 AMLiking images of up to 5 followers of acropixie
11:19 AMTrying to get user data from HTML
11:19 AMNavigating to user acropixie
11:19 AMGoto https://www.instagram.com/acropixie
11:19 AMPage loaded
11:19 AMWaiting 3.67 sec
**11:19 AMFailed to get user data from page SyntaxError: Unexpected token u in JSON at position 4466**
11:19 AMNeed to intercept network request to get user data
11:19 AMUnable to intercept request, will send manually
11:19 AMHas more pages (current 1)
11:19 AMUser followers batch kelly_kpwell,awimbawe,ramvijar17,the_rogueroad,stevmaster33,abolfazlmm,autumncecilia_,garasimiakviktoriia,carlosmorel423,denniwillo

...

11:23 AMTrying to get user data from HTML
11:23 AMNavigating to user kelly_kpwell
11:23 AMGoto https://www.instagram.com/kelly_kpwell
11:23 AMPage loaded
11:23 AMWaiting 2.52 sec
**11:23 AMFailed to get user data from page SyntaxError: Unexpected token u in JSON at position 5372**
11:23 AMNeed to intercept network request to get user data
11:23 AMUnable to intercept request, will send manually
11:24 AMUser has too many followers compared to follows or opposite, skipping
11:24 AMTrying to get user data from HTML
11:24 AMNavigating to user awimbawe
11:24 AMGoto https://www.instagram.com/awimbawe
11:24 AMPage loaded
11:24 AMWaiting 2.12 sec
**11:24 AMFailed to get user data from page SyntaxError: Unexpected token u in JSON at position 3544**
11:24 AMNeed to intercept network request to get user data
11:24 AMUnable to intercept request, will send manually
11:24 AMFollowing user awimbawe
11:24 AMWaiting 5.49 sec
11:24 AMWaiting 1.71 sec
11:24 AMWaiting 59.24 sec
11:25 AMHave reached daily follow/unfollow limit, waiting 10 min
11:25 AMWaiting 1123.69 sec`

**Comment by mifi** [comment]
this is normal
