### ISSUE TITLE
Try the troubleshooting button. Error: User not found

### ISSUE THREAD

**Issue by the4kw** [mifi/SimpleInstaBot#162]
Yesterday I used the bot for the first time and it worked well as far as I can tell. This morning I received this error message:

> Failed to run
> Try the troubleshooting button. Error:
> User not found

i use the 1.11.1

**Comment by mifi** [comment]
what do u see on the page when it happens? does it happen every time when starting up? any logs?

**Comment by the4kw** [comment]
> Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. [Go back to Instagram.](https://www.instagram.com/)

```
6:50 PMUser followers batch akshobhyia,vereina.botoncito,dermotrussell.bw,dbhrndt,osara_ph,doc_winkler_photography,carldemaia,bruceedwardhall,geoffroyschied,rosa_lightart,_bsour,felipe._.ramos,monsieur.berlinois,flowoderso,ursikodesign,luca.labbadia,___.nicki.__,vernderlust_97,gorkym,byglendavid,dlund.foto,rikelenz,stvn.krb,masterbradley,benita.dasilva,sojidaabdullajonova,loic_schvan,t.o.m.a.i.g.c.o,martinezbrucartagena,eliott_drr,jakobbisi_ph,_david_stein,xoxo._oz,laaraa122,kap.by.eve,larsschneidervisuals,find_a_frame,5__2mn,oh.doonan,flitze71,phoenixtatjana,yogalissa_,outofframe,franztanzt,mill_ian,mrwh1tecom,karina_syndicus
6:50 PMTrying to get user data from HTML
6:50 PMNavigating to user akshobhyia
6:50 PMGoto https://www.instagram.com/akshobhyia
6:50 PMPage loaded
6:50 PMWaiting 2.47 sec
6:50 PMCannot find text "akshobhyia" on page
6:50 PMFailed to process follower akshobhyia Error: User not found
6:50 PMWaiting 33.44 sec
6:51 PMTrying to get user data from HTML
6:51 PMNavigating to user vereina.botoncito
6:51 PMGoto https://www.instagram.com/vereina.botoncito
6:51 PMPage loaded
6:51 PMWaiting 2.04 sec
6:51 PMCannot find text "vereina.botoncito" on page
6:51 PMFailed to process follower vereina.botoncito Error: User not found
6:51 PMWaiting 34.37 sec
```

**Comment by teddybeaar** [comment]
I'm also getting the same error! Replacing my IG handle with "xxxxxx"

11:55 AMNo cookies found
11:55 AMSetting language to English (en)
11:55 AMWaiting 1.31 sec
11:55 AMWaiting 5.22 sec
11:55 AMFound language selector
11:55 AMAlready English language
11:55 AMWaiting 1.97 sec
11:55 AMNo login page button, assuming we are on login form
11:55 AMWaiting 1.66 sec
11:55 AMWaiting 1.33 sec
11:55 AMWaiting 10.21 sec
11:55 AMSetting language to English (en)
11:55 AMWaiting 1.03 sec
11:55 AMWaiting 4.39 sec
11:55 AMFound language selector
11:55 AMAlready English language
11:55 AMSaving cookies
11:55 AMHave followed/unfollowed 0 in the last hour
11:55 AMHave followed/unfollowed 150 in the last 24 hours
11:55 AMHave liked 7 images in the last 24 hours
11:55 AMTrying to get user data from HTML
11:55 AMNavigating to user mallcrwlin_t4r
11:55 AMGoto https://www.instagram.com/xxxxxx
11:55 AMPage loaded
11:55 AMWaiting 2.30 sec
11:55 AMCannot find text "xxxxxx" on page
11:55 AMFailed to run Error: User not found

**Comment by mifi** [comment]
any screenshot of what you see on-page? or html (see instructions here https://github.com/mifi/SimpleInstaBot/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by sapirkalbin** [comment]
same here for me and a friend

**Comment by sapirkalbin** [comment]
starting with a red message "no cookies found"

**Comment by mifi** [comment]
Closing this because I think it's the same as #142
