### ISSUE TITLE
Day/Night behavior - not working or setup required?

### ISSUE THREAD

**Issue by ediooo** [mifi/SimpleInstaBot#168]
I am running your bot 24/7 on a PI, no issues so far except:
It appears to never stop. I am using very conservative settings but in the feature list there is some "night/day" behaviour listed.
So that it would be inactive at night. 
Do I need to set this up somewhere? I could not find a setting and currently, my bot just keeps going uninterupted.
Thanks!

**Comment by mifi** [comment]
Set a low value for maxFollowsPerDay

**Comment by mifi** [comment]
Dup of #164
