### ISSUE TITLE
Failed to run TimeoutError

### ISSUE THREAD

**Issue by Sobhanes** [mifi/SimpleInstaBot#172]
it logs in successfully but before doing anything I face this error:

 **Failed to run TimeoutError: Navigation timeout of 30000 ms exceeded**

**Comment by mifi** [comment]
does it happen every time? what do you see?

**Comment by Sobhanes** [comment]
it happens almost every time. it only worked well once but after changing a settings its not working again.
now when I ran it again to send the screenshot of error it worked !! ( second time working after about 8 or 9 times trying)
I'll leave a pic here if it happened again.

**Comment by Sobhanes** [comment]
![1](https://user-images.githubusercontent.com/112699617/188167431-bd1cfb34-8795-436d-bf2c-6db821b85057.PNG)
here's the error...

**Comment by mifi** [comment]
does the instagram browser window pop up at all?

**Comment by Sobhanes** [comment]
yes it does and then logs in. here I edited out.

**Comment by mifi** [comment]
what's happening in that window after it logs in? any loading of a page etc? you can open developer tools to check if anything is going on.

**Comment by Sobhanes** [comment]
it first goes to settings after logging in , then I face this in logs:
Failed to set language, trying fallback (cookie) TimeoutError: Navigation timeout of 30000 ms exceeded
afterwards it goes to home page in instagram and then without nothing happening there the error I shared earlier pops up .
I can't figure out what's going on in developer toools.

**Comment by mifi** [comment]
does it happen on other computers or other accounts too?
