### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by gioelefelice** [mifi/SimpleInstaBot#174]
Hi, this is my error, i've read other similar problem but i have no understand how fix it, can u help me?

![Immagine 2022-09-03 205335](https://user-images.githubusercontent.com/22278714/188284511-efad0f9d-7aa1-4860-a7e7-65d75e09ac5b.png)

![Immagine 2022-09-03 205458](https://user-images.githubusercontent.com/22278714/188284513-4f4f16a9-36fa-4391-baec-50e24ba0b81b.png)

**Comment by mifi** [comment]
See #142 - i think you're being temp blocked by instagram. try to wait for a while or see suggestions in that issue
