### ISSUE TITLE
"Button did not change state"

### ISSUE THREAD

**Issue by aizarged** [mifi/SimpleInstaBot#178]
Good morning! I have been using the bot for a few days without any issues, I am using it in a way that is not aggressive for Instagram to find out that it might be a bot running (Just 30 followers per day, 5 per hour).
But lately I always get the same error anytime the bot tries to follow, or unfollow someone's account:

"Button did not change state"

Here goes a screenshot of the issue:

<img width="571" alt="InstaBot  1 11 1" src="https://user-images.githubusercontent.com/92083870/189472854-856cb4d1-ace3-419f-8437-95984529d14e.png">

 - OS: [MacOs Monterey 12.4]
 - Browser [Chrome]

**Comment by mifi** [comment]
what did you see on the browser page? could you try to copy-paste html so we can see how the button looks like in html?

**Comment by aizarged** [comment]
Hello again,

I figured out the issue: I was filming my screen in order to capture the behavior of the bot in addition to the HTML...while filming I noticed that it was working perfectly, so I just realized that having the Bot windows on a different "Desktop" instance on the Mac is what was causing the problem!
Hope it helps.
Thanks for your answer and your help!

**Comment by mifi** [comment]
that's odd! but thanks for providing the data point. maybe helpful to others in the future

**Comment by aizarged** [comment]
I think the bot thinks/sees itself as minimized while operating on another desktop window different from the one I am currently working on.
