### ISSUE TITLE
Only liking photos without following?

### ISSUE THREAD

**Issue by galinickel** [mifi/SimpleInstaBot#18]
Hi! is it possible to only like a few photos from every user instead of following them as well? 
since it is possible to follow and not like any photos, i wonder if it can be possible to just like without following?

**Comment by mifi** [comment]
Got a comment from someone on email:

> Instagram seems to give a great deal about follow /unfollow. But what about if you make it so that I can set follow /unfollow to 0 and instead only use the like option. The result may be almost the same, maybe even better, because people kinda may react suspicious if they see me following them but they might click my account and view it when I like their pictures only. I would think Instagram would not crush down so hard on only liking pictures.

so only liking may reduce the chance of getting a "suspicious" notice

**Comment by mifi** [comment]
this is now implemented using the option `set enableFollowUnfollow: false`
