### ISSUE TITLE
Most recent version on Raspi

### ISSUE THREAD

**Issue by ediooo** [mifi/SimpleInstaBot#183]
Hi,
I am running Simpleinstabot 1.11.1 on Raspi. 
Is this the most recent version? If not, how can I update to the most recent one?

Thanks so much for your help!

**Comment by mifi** [comment]
see https://github.com/mifi/SimpleInstaBot/releases

**Comment by ediooo** [comment]
Thanks! What is the update process when there is a new release? So that the data (unfollowed list etc) stays intact?

**Comment by mifi** [comment]
just unpack/replace files
