### ISSUE TITLE
BOT Fail to unfollow

### ISSUE THREAD

**Issue by saabtech** [mifi/SimpleInstaBot#185]
The Bot open IG user menu to unfollow, but does not unfollow instead moves to next user and repeat the cycle. The Bot log says it has unfollowed, I checked the followings of my account and they stay the same. This can be probably due to new interface of Instagram.

**Screenshots**
![image](https://user-images.githubusercontent.com/85780689/194810265-14c880e9-4836-4b89-a1fa-a9e79c0e590f.png)

 - OS: win7
 - Browser chrome
 - Version: 106.0.5249.103
 - BOT version: 1.11.1

**Comment by mifi** [comment]
dup #181
