### ISSUE TITLE
MFA Code - Add a "Pause button" to type MFA code manually (Authentication)

### ISSUE THREAD

**Issue by Myastr0** [mifi/SimpleInstaBot#188]
Hey!

Instagram forced me to enable MFA on my pro account and unfortunately SimpleInstaBot does not allow bypassing authentication via MFA. (Enter a MFA code or whatever). Is it possible to add an option to pause the bot to type MFA code manually on the desktop app (not possible in headless i guess).

Happy to help you to implement these feature but i need documentation to understand the code architecture !

**Comment by mifi** [comment]
if there's an error or blockage after login, the bot is already supposed to pause and let you do manual intervention. does that not work? could you record what's happening when you login or explain a bit better? the bot code itself is here: https://github.com/mifi/instauto no docs but it should be fairly straightforward

**Comment by Myastr0** [comment]
Oh, I didn't know this behavior. After one another try, i see that the bot stop and let me login manually ! Sorry for the feature request, i close this issue.. Thanks for your reply @mifi !
