### ISSUE TITLE
Don't like posts of already followed users

### ISSUE THREAD

**Issue by AndreaCorallo** [mifi/SimpleInstaBot#192]
**To Reproduce**
normal operation mode

**Desktop (please complete the following information):**
 - GNU/Linux
 - Appimage
 - Version 1.11.1

**Additional context**
The bot likes posts of users the main account is already following and/or are already following the main account

**Comment by mifi** [comment]
closing in favor of #187

**Comment by AndreaCorallo** [comment]
I guess this one has been closed because the fix is the same as for #187 ?

**Comment by mifi** [comment]
yup! very related. i took the liberty of editing your post to add also liking

**Comment by AndreaCorallo** [comment]
Thanks for your work

  Andrea
