### ISSUE TITLE
CSRF token incorrect or missing

### ISSUE THREAD

**Issue by angelopouloschristos** [mifi/SimpleInstaBot#196]
I have troubles since 1 week that i'm trying to solve. When the bot is trying to login to instagram, it shows a message "CSRF token incorrect or missing". I tryed to change user agent to chrome/mozilla, still same issue. I host the bot on a OVH VPS ubuntu. 

Do someone have an idea how i could solve this issue ?

Thanks everyone !

**To Reproduce**
When the bot connect a error message under the login button of instagram "CSRF token invalid" 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: default

**Comment by angelopouloschristos** [comment]
Up please

**Comment by mifi** [comment]
does it happen for different accounts? what about different ip addresses?

**Comment by angelopouloschristos** [comment]
Nope, i use the bot on a VPS ... and apparently it's the VPS that does not work anymore.
Maybe does it mean something like IP BAN ??????

On the same VPS i installed a VPN and now it works

**Comment by mifi** [comment]
see readme. don't run on a VPS, VPN or cloud IP. use a home ip address
