### ISSUE TITLE
liking posts?

### ISSUE THREAD

**Issue by galinickel** [mifi/SimpleInstaBot#2]
hey :) 
i was wondering if its possible for the bot to like posts rather than do follows?
if so, is it possible to configure the bots activities and change them? i find that for my account liking 4-6 posts from a user's follower does way better than follow-unfollow trick.

**Comment by mifi** [comment]
Hi. this has not yet been implemented as the bots focus was to do one thing and do it well. But pull requests are welcome!

**Comment by mifi** [comment]
This is now implemented!
