### ISSUE TITLE
Try the troubleshooting button. Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Forstellaire** [mifi/SimpleInstaBot#203]
I got a problem with simpleInstaBot, can you try to fix it please ? 
![Sans titre](https://user-images.githubusercontent.com/34395400/201535319-2f406181-cbda-4bfe-851c-3a7363ae731c.png)

 - OS: Windows 10
 - Browser Chrome

**Comment by Forstellaire** [comment]
LOGS FROM LAST RUN
6:23 PMNo cookies found
6:23 PMSetting language to English (en)
6:23 PMWaiting 1.08 sec
6:23 PMWaiting 3.97 sec
6:23 PMFailed to set language, trying fallback (cookie) Error: Language selector not found
6:24 PMWaiting 1.22 sec
6:24 PMWaiting 1.30 sec
6:24 PMWaiting 5.00 sec
6:24 PMNo login page button, assuming we are on login form
6:24 PMWaiting 1.79 sec
6:24 PMWaiting 1.62 sec
6:24 PMSetting language to English (en)
6:24 PMWaiting 1.32 sec
6:24 PMFailed to set language, trying fallback (cookie) Error: net::ERR_ABORTED at https://www.instagram.com/accounts/edit/
6:24 PMWaiting 1.12 sec
6:24 PMWaiting 1.40 sec
6:24 PMWaiting 4.17 sec
6:24 PMSaving cookies
6:24 PMHave followed/unfollowed 0 in the last hour
6:24 PMHave followed/unfollowed 27 in the last 24 hours
6:24 PMHave liked 12 images in the last 24 hours
6:24 PMTrying to get user data from HTML
6:24 PMNavigating to user djayce_rs
6:24 PMGoto https://www.instagram.com/djayce_rs
6:24 PMPage loaded
6:24 PMWaiting 2.22 sec
6:24 PMUnable to get user data from page (TypeError) - This is normal
6:24 PMNeed to intercept network request to get user data
6:24 PMUnable to intercept request, will send manually
6:24 PMFailed to manually send request Error: Evaluation failed: SyntaxError: Unexpected token < in JSON at position 0
6:24 PMFailed to run SyntaxError: Unexpected token < in JSON at position 0

**Comment by mifi** [comment]
does it happen every time? for other accounts too?

**Comment by joaocampos84** [comment]
hello, same error here! any solution?
Thanks
