### ISSUE TITLE
Suddenly can't unfollow

### ISSUE THREAD

**Issue by c-chytoudis** [mifi/SimpleInstaBot#206]
**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox, Edge
 - Version both 107 

I would like to share something weird. I realized that when I logged in at Instagram website I can't unfollow anymore. Even bot which uses instagram web version can't unfollow (without errors)

The pop up message when I press "unfollow" button does not appear anymore. Is it a ban? However, when I use instagram app (iOS) it works fine (follow, unfollow etc).

https://user-images.githubusercontent.com/77646310/202807800-c54f4b03-eb3f-4377-94e3-29617c45214c.MOV

I unfollowed it from Instagram app (iOS) and I followed it again from Instagram web version. Still the same issue.

https://user-images.githubusercontent.com/77646310/202810059-9cc654c0-42f2-46f2-9976-ab6d49611b6c.MOV

**Comment by mifi** [comment]
you could check developer tools for any error but yea probably it's a a temporary block, not much to do about it for simpleinstabot

**Comment by wyarex** [comment]
Same exact issue happened to me a couple days ago

**Comment by c-chytoudis** [comment]
> Same exact issue happened to me a couple days ago

Hello, I **can** follow / unfollow while using the instagram app but I **can only follow** while using the instagram website. Do you have the exact same problem?

**Comment by wyarex** [comment]
Yes same behavior on my end

**Comment by c-chytoudis** [comment]
Hello, finally the problem solved. It was instagram's bug while pressing **unfollow** button. I saw today different pop-up menu when button is pressed!
