### ISSUE TITLE
Error for follow

### ISSUE THREAD

**Issue by Pamthenooby** [mifi/SimpleInstaBot#207]
**To Reproduce**
I run the bot normally.

**Screenshots**
![PrtScr capture_1746](https://user-images.githubusercontent.com/118735929/203192301-13110af4-ba4c-419b-8e68-646519ae1fe7.jpg)
There is the same Error line : "Failed to process follower XXX Error: Button did not change state"
It's mean it dosn't follow this user ? 

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser : chrome
 - Version : 107

**Provide me with HTML**

Did you receive an error while the bot is running? Yes
I notice it's the same red line error concerning Follow fonction.

Data is stored in an folder automatically ? 
Thanks for your help !

**Comment by mifi** [comment]
what do you see in the instagram page?

**Comment by Pamthenooby** [comment]
It's possible that it's IG who block the bot ?

**Comment by mifi** [comment]
Unfortunately I don't see any of your screenshots of the instagram window showing what it looks like after trying to unfollow
