### ISSUE TITLE
Sorry, this page isn't available

### ISSUE THREAD

**Issue by Scerlok97** [mifi/SimpleInstaBot#209]
when starting the bot tries to enter my account but this text is displayed (sometimes only on my account other times on all), this problem also happened during the session so not with my account but with an account random, this problem occurred not only with the pc described in this post but also with another pc with an i7 6500 and w-10 at x64

al momento dell'avvio il bot cerca di entrare nel mio accont ma viene visualizzata questa testo(alcune volte solo sul mio account altre volte su tutti), questo problema è accaduto anche durante la sessione quindi non con il mio account ma bensi con un account random, questo problema si è verificato non solo con il pc descritto in questo post ma anche con un altro pc con un i7 6500 e w-10 a x64

**Screenshots**
![image](https://user-images.githubusercontent.com/102485459/203841148-3dd4e875-d9f7-47dc-bec8-309c57c26ea4.png)
![image](https://user-images.githubusercontent.com/102485459/203842061-ae836cb3-62e5-469f-bc2a-36ab9f691356.png)

**Desktop
 - OS: [windows 11]
 - Browser [chrome]
 - Version bot [1.11.2]

**Comment by mifi** [comment]
I believe this is a duplicate of #142
