### ISSUE TITLE
Follow "likers" 

### ISSUE THREAD

**Issue by yadavneeraj1003** [mifi/SimpleInstaBot#218]
I want to request you to please add the feature to follow "likes" of a post or an account. I want to follow only likes. I tried extracting likers using a tool and use it in the bot to follow but it didn't work. For example, if I add 10 users that I have extracted, then after rfew follows I closed the software. Then the custom user list is gone. I don't know if I  need to add new users everytime I run the software or what? Can you please tell me the proper method or implement the option to follow likers? It would be really very helpful for anyone as the likes are more active than just active users.

**Comment by mifi** [comment]
i believe dup of #39
