### ISSUE TITLE
Not liking followers pictures

### ISSUE THREAD

**Issue by codewire132** [mifi/SimpleInstaBot#22]
Great program but after 2 days of using it it's not liking anymore any fix?

**Comment by mifi** [comment]
See https://github.com/mifi/instauto/issues/30

For me it's working. Only sometimes it doesn't work. Do you see anything different in the instagram interface? could you take a screenshot?

**Comment by mifi** [comment]
![1601150049450](https://user-images.githubusercontent.com/402547/94362321-c9884480-00ba-11eb-9cf9-2094a045c901.jpg)

After taking a screenshot upon the error, I got this. So it seems to be caused by some kind of throttling from instagram's side.

**Comment by codewire132** [comment]
Anyway to fix it?

**Comment by mifi** [comment]
Don't know what is causing it

**Comment by codewire132** [comment]
The thing is that of i launch insta via safari of something then I can like pictures without a problem but if the bot launches then it doesn't like?

**Comment by mifi** [comment]
Chrome also works? (the bot uses chrome)

**Comment by codewire132** [comment]
Yes that also work I think Instagram detects the renderer

**Comment by codewire132** [comment]
Fix

I found a fix and it was the most simplest thing I log out and back in and everything works great again for me 

I also want to thank you for your kindness and this program that you've made great job keep going 👍
