### ISSUE TITLE
BOT goes to sleep shortly 

### ISSUE THREAD

**Issue by saabtech** [mifi/SimpleInstaBot#230]
I receive " {"data":{"user":{"edge_followed_by":{"count":43933,"page_info":{"has_next_page":false,"end_cursor":null},"edges":[]}}},"extensions":{"is_final":true},"status":"ok"}" 

When the bot run for couple of hours ( 2-3hours ) it goes to sleep. Happens every day and I have to restart the BOT again. Never happened before.

Any suggestion

**Comment by rishibaghel25** [comment]
you're using pc or laptop ??
if laptop then change your laptop inactivity sleep timeout because code is working properly.

**Comment by saabtech** [comment]
> you're using pc or laptop ?? if laptop then change your laptop inactivity sleep timeout because code is working properly.

I am using Desktop, I will change the power management option and disable all sleep mode. Will let you know the updates.
