### ISSUE TITLE
App does not wake after sleeping

### ISSUE THREAD

**Issue by lo1gr** [mifi/SimpleInstaBot#26]
Happens both for the app downloaded from the website and run from the terminal. Anyone else has this issue of having to restart the application in order for it to work again (and unfortunately potentially "re"following accounts you already followed the day before) ?

**Comment by mifi** [comment]
MacOs or windows or?

**Comment by mifi** [comment]
and how does the app look like after resume?

**Comment by mifi** [comment]
closing in favor of #23
