### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by mifi** [mifi/SimpleInstaBot#27]
Support for multiple accounts inside the app (and running multiple instances of the app) has been requested.

As of now you can **not** run multiple instances of the bot on the same computer (same user), as it will cause conflicts.

Potential issues:
- Need to prevent conflict with stored files like cookies.json, followed.json etc. (Store one file per account)
- This may cause more throttling by Instagram to the point that it will reduce the effectiveness of running multiple accounts (because they see more requests from the same IP on multiple accounts)

**Comment by tomasliachovskis** [comment]
Hello @mifi can you tell what is the logic for multiple acc, shall use multiple chromium instances or is possible do that in separate tabs ?

**Comment by mifi** [comment]
Hi. It's not supported right now, because of the stored state files

**Comment by rocko145** [comment]
> Hi. It's not supported right now, because of the stored state files

Can I please add as a suggestion ability to specify where the app data is stored, so when running multiple instances they use different credentials, followers etc.

**Comment by rocko145** [comment]
Btw, can I hardcode the directory of state files and build an app for a mac by myself for now?

**Comment by mifi** [comment]
Yes you can, but I cannot assist you with how to build, some hints though:
```bash
npm start
```

```bash
npm run pack-win
npm run pack-mac
npm run pack-linux
```
Alternatively see https://github.com/mifi/SimpleInstaBot/blob/master/.github/workflows/build.yml

**Comment by abides** [comment]
In windows 10 %appdata% is C:\Users\%username%\AppData\Roaming\SimpleInstaBot so its different for each user by default. I installed the 2 different user in same computer and both have different %appdata% folder. Is there any other thing i need to consider?

**Comment by mifi** [comment]
I think that should work, yes. You may have higher risk of being blocked but other than that I cannot think of anything.

**Comment by kingbotss** [comment]
Check my code. Added support for multiple accounts.

https://github.com/kingbotss/SimpleInstabotMulti

**Comment by mifi** [comment]
That’s cool! If you create a PR i can see whether it’s something we can merge

**Comment by mifi** [comment]
newest version now supports multiple accounts, by using command line argument. see readme.
