### ISSUE TITLE
Does this works?

### ISSUE THREAD

**Issue by Niikk0o** [mifi/SimpleInstaBot#3]
Hey. I want to know if this works or not. Please tell me. Thank you.

Following and Unfollowing. I will be doing only 100 actions per day or even less. Like 30 actions per day. ( Or this app will get me action banned? )

**Comment by mifi** [comment]
It works for some but some will get an Action Blocked message. You can try it and see. Under advanced settings you can configure max number of follow/unfollow per day etc.

**Comment by mifi** [comment]
See #1
