### ISSUE TITLE
Bot follows more than unfollows

### ISSUE THREAD

**Issue by nocomment-bln** [mifi/SimpleInstaBot#30]
Hey Mikael

The Bot is now running for more than 2 weeks.

I started with 250 people following and now I am following 650.
I think I should follow much less.

Here is my config.

`{
  "maxFollowsPerDay": 120,
  "maxFollowsPerHour": 20,
  "maxLikesPerDay": 70,
  "maxLikesPerUser": 5,
  "followUserRatioMin": 0.2,
  "followUserRatioMax": 4,
  "followUserMaxFollowers": 3000,
  "followUserMaxFollowing": 1500,
  "followUserMinFollowers": 40,
  "followUserMinFollowing": 10,
  "dontUnfollowUntilDaysElapsed": 3,
  "runAtHour": 9
}

Is this a bug or has it to do something with my config?`

**Comment by nocomment-bln** [comment]
Any Idea?

**Comment by mifi** [comment]
Hi, This seems normal.
with `"dontUnfollowUntilDaysElapsed": 3` and `"maxFollowsPerDay": 120`

`250 + 120 * 3 = 610`

or am I miscalculating

**Comment by nocomment-bln** [comment]
Thanks for calculating that for me 👍  :) Sounds right but now I am following 831.. 👎  Any Ideas ?

**Comment by mifi** [comment]
THB I'm not 100% sure about my calculations either.
Actually I think I found a bug. The bot was unfollowing less than it was following every day. I have now incrased this so it will instead first unfollow 2/3 of the daily limit, then follow 1/3 of the limit.

**Comment by mifi** [comment]
Try again with version 1.5.1 when it's done building. In theory your following count should now slowly decrease over the next days.

**Comment by nocomment-bln** [comment]
Thanks! I am running your APP on Ubuntu. How can I update it ? Where is the Database stored ?

**Comment by mifi** [comment]
Just download and install the newest version like you did the first time from here: https://github.com/mifi/SimpleInstaBot/releases/tag/v1.5.1

settings should be stored in your user directory

**Comment by nocomment-bln** [comment]
yes worked! thanks (: so lets what and see if its working now :)

**Comment by mifi** [comment]
Is this fixed now?

**Comment by nocomment-bln** [comment]
yes, thanks!
