### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by codewire132** [mifi/SimpleInstaBot#33]
Hey man love your project been using it allot but yesterday I got myself I little raspberry pi so I thought it would be perfect to have your program run 24/7 but I'm not able to run it I'm running raspberry pi os 64bit can anyone help?

**Comment by thalst** [comment]
Just chmod +x the appimage and then execute ./Simple...Appimage

**Comment by rocko145** [comment]
I'm getting "Failed to run, the parameter "browser" was not passed in on Xubuntu.
Has anyone had such an issue?

**Comment by codewire132** [comment]
Ty it works now
