### ISSUE TITLE
Restoring state after closing the program

### ISSUE THREAD

**Issue by apollotsantos** [mifi/SimpleInstaBot#34]
Hi,

Is it possible to "continue" the bot after closing it? I mean, if the bot followed 10 people and I close it, will it remember to unfollow that 10 people when I reopen it on a certain date? I've seen you talk about it on other issues, but I think it would be great to have this information explicit on Readme.

Thanks for the great software!

**Comment by mifi** [comment]
Yes it will remember which are followed and later unfollow them. I will update readme
