### ISSUE TITLE
Auto language selection seems broken

### ISSUE THREAD

**Issue by luluunik** [mifi/SimpleInstaBot#38]
Hello, (first sorry for my english)

When i try to connect on mac, it seems regognise everything until a  message about save username and password appears then it cannot log because of the window. I try to manually register later, then i'm  connected on my account but simpleinstabot still saying it cannot logs.

**Comment by mifi** [comment]
hi. can you provide a screenshot?

**Comment by luluunik** [comment]
![1](https://user-images.githubusercontent.com/49833786/105761280-3cafa380-5f53-11eb-9df3-3a0e9a84ed23.jpg)
![2](https://user-images.githubusercontent.com/49833786/105761289-3e796700-5f53-11eb-84d6-5eea645340a0.jpg)
### 

Yes :) I had to click on "plus tard" for stop reloading and when i arrive on my account connected..nothing 

Thanks a lot

**Comment by mifi** [comment]
oh. for some reason it's failing to set your language to english. can you try to manually do that?

**Comment by luluunik** [comment]
Oh okay you are right ! I'll try and come back here to tell! Thanks

**Comment by luluunik** [comment]
Oh wow! it works! Thank you !

**Comment by mifi** [comment]
Cool! I want to leave this issue open though, because it seems that language selection is broken or something
