### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by tiotrom** [mifi/SimpleInstaBot#4]
I add the login details and everything it needs to, but when I click START it opens another window with the Instagram LogIn page for a second or so then it closes it and it says it failed. Basically I think it cannot add the login credentials by itself. I tried adding them manually super fast before that window closes, but even that didn't work. I am using the last appimage and arch. Cheers!

**Comment by mifi** [comment]
Thanks for reporting.
It seems that instagram changed the login page. I have now adjusted the code. Try newest version.
