### ISSUE TITLE
Question - How to run two bot instances on mac?

### ISSUE THREAD

**Issue by rocko145** [mifi/SimpleInstaBot#40]
Hello. 
I'm trying to run two bot instances on a Mac. 
I copied the app to a different dir and launched two instances simultaneously, but both use the same credentials, pages to follow.
Is it possible to separate them completely so they use different data each?

**Comment by rocko145** [comment]
As a suggestion it would be great if I could specify the directory where to store the app data(creds, pages to follew etc).

**Comment by mifi** [comment]
Dup #27
