### ISSUE TITLE
Can you run 2 apps on 1 computer at the same time

### ISSUE THREAD

**Issue by mikikuke** [mifi/SimpleInstaBot#41]
I love your app, it works just great. 
Is it possible to run 2 apps on 1 computer? And how?

Also I used instazood before and the only difference is that you can follow hashtags there and also there was a comment generator, where the app commented on user posts....will this come in the future?

**Comment by mifi** [comment]
Dup of #27 #31 #29

**Comment by kingbotss** [comment]
Check #27
