### ISSUE TITLE
Allow bot to start at runAtHour when clicking "Start Bot"

### ISSUE THREAD

**Issue by martiGIT** [mifi/SimpleInstaBot#45]
Hi! 
It would be nice to start bot not just after "start bot" button is pressed, but on its hour defined in 
`runAtHour`
It would be useful for situation when I would like to change config (add/remove source profiles) when bot is in his "long sleeping" time, but would not start bot immediately after the start button is pressed. 
So as a suggestion - maybe just another button to "start with cron" despite of existing "Start Bot" button.  
Additionally - it would also be useful that "stop bot" would not close whole application, just stop bot operations. 

Thanks for your comments
Best regards,
Marcin

**Comment by mifi** [comment]
Hi. I have now added a setting for this, so it will be out in the next version.
Stop bot is not possible right now, but have added it to a refactoring issue #46
