### ISSUE TITLE
High CPU on RPi

### ISSUE THREAD

**Issue by mifi** [mifi/SimpleInstaBot#49]
... has been reported.
I suspect it is caused by the lottie animation

**Comment by apollotsantos** [comment]
I also have an enormous cpu usage on normal linux Machine. Its a core2duo with load average 13.25 with 4 instances of the bot open. Let me know if you need VNC access for testing some solution. I can provide you with an user.

**Comment by apollotsantos** [comment]
I can confirm the Lottie animation caused it. With 4 instances running on my server, I've got a load of **16~18**.

Now I've recompiled the bot without any Lottie, and the computer is usable again. The load is **1.5**!!!

I was leaving this specific computer dedicated to the bot, as it made the PC unusable, but now we know the problem.
@mifi 

In the attached image, you can see the residue left on the load by using the original version, and the more recent load with no Lotties.
![image](https://user-images.githubusercontent.com/25730751/111483454-8e82d780-8713-11eb-93fd-009d46e31507.png)

**Comment by mifi** [comment]
Thanks for researching! It's a pity that the cute little robot is wasting so many cpu cycles. may have to replace him (or stop him after a few mins)

**Comment by sw2000** [comment]
I also get very high CPU usage on Manjaro Linux
