### ISSUE TITLE
How to run on Pi?

### ISSUE THREAD

**Issue by t0bse** [mifi/SimpleInstaBot#55]
How do i run the arm7 package on my raspberry pi?

**Comment by mifi** [comment]
did you get it to work? probably `tar xvf` then run the exe?

**Comment by KEKLBruh** [comment]
on pi, there isn't an exe? how to open the program

**Comment by mifi** [comment]
```bash
# Download the Raspberry Pi binary
wget https://github.com/mifi/SimpleInstaBot/releases/latest/download/SimpleInstaBot-linux-armv7l.tar.bz2
tar xvf SimpleInstaBot-linux-armv7l.tar.bz2
cd SimpleInstaBot-linux-armv7l
./simpleinstabot
```

**Comment by mifi** [comment]
iupdated readme

**Comment by t0bse** [comment]
thank you! maybe you could complete the readme with autostart/run in background? :)

**Comment by t0bse** [comment]
> 1. autostart bot is not possible now. need to manually press the start button to start. but that could be a (separate) feature request.
> 2. run on boot depends on the OS and desktop setup. i'm not sure how to do this on raspbian with the built in desktop env
> 3. run in background, i'm not sure what's the need for that. do you mean minimize the window?

i mean close the terminal-window and it's still running. that's possible on pi, had that running a while ago - but don't know how to anymore :D

**Comment by birdman769** [comment]
**either:** 

sudo DISPLAY=:0 ./simpleinstabot --no-sandbox
DISPLAY=:0 ./simpleinstabot --no-sandbox

**results in:** 

(simpleinstabot:957): Gtk-WARNING **: 09:57:33.670: cannot open display: :0


**and:** 

DISPLAY=:0 ./simpleinstabot

gives me the same problem. Any help with this would be greatly appreciated!  Thanks :)
