### ISSUE TITLE
login doesn´t work, failed to run

### ISSUE THREAD

**Issue by xldbx** [mifi/SimpleInstaBot#6]
Tried the newest autoinstaller version from here (win) 
https://mifi.github.io/SimpleInstaBot/
Bot window is starting and i can click on START
But directly after the new window is opened and the creds to login were inserted it crashes with "Failed to Run". Tested with several accounts, which are all working when i login manually.

checked the console. Error is:

main.24d9e999.chunk.js:1 TypeError: Cannot read property 'click' of undefined
    at module.exports (C:\Users\X\app.asar\node_modules\instauto\index.js:551:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.initInstauto

**Comment by mifi** [comment]
I get this issue too now. They changed something. Seems they are serving up a different login page to the bot. will investigate more.

**Comment by mifi** [comment]
Actually I got a different error, but I was testing with an old version. What did the bot window show when it crashed? The reason it crashes is because it cannot find the login button. Was there a login button there? What was the text inside of it? Did you have english set as language?

**Comment by mifi** [comment]
I think this was caused by language. I have now added to the code so that it changes language to english before trying to log in. Hopefully it will solve it

**Comment by mifi** [comment]
Try the newest version now.

**Comment by xldbx** [comment]
hi @mifi , thx for your response :) 
language was english.
bot is starting now with the newest version. 

not sure what it´s doing right now, because nothing is changing in the new window. it checked the accounts and the count upfront which i´m following and now no changes anymore (and no new followings). I'm just gonna let it run for a few hours and watch it...

**Comment by mifi** [comment]
How long did you wait? usually it sleeps for 10-60 seconds every now and then between actions

**Comment by xldbx** [comment]
i´m running it for 30min right now, but no new followings.
_stuck window was a plain json output with a count of followings and a couple of follower names._ 

i restarted the bot again, and modified the username list (had 20 before, now 3). 
now the bot starts, and i see instagram in the second window (logged in, so not the plain json anymore). it opened 2-3 random accounts(not from my username list) and then stopped on the 3 one. its opened, but nothing happen. 

i changed now the userlist to only 1 account with only 80 followers (to see if a big number of followers is a prob). logged in, it goes through 2-3 random accounts and then nothing happen anymore. no new followings (settings are default )
![test](https://user-images.githubusercontent.com/62890127/78356078-3361de80-75af-11ea-89fd-e45eab417f4d.JPG)
)

**Comment by mifi** [comment]
I think that was a bug. Have made some improvements now. Please try newest version 1.2.2.

And btw if you havent set daily follow limit yet, i would recommend to set it to 150 and hourly to 20 (maybe can increase later)

**Comment by xldbx** [comment]
thx man, testing right now :)

**Comment by xldbx** [comment]
following works now :) thx for adding the logging console.

**Comment by mifi** [comment]
awesome. please report back if there are any issues
