### ISSUE TITLE
Button did not change the state

### ISSUE THREAD

**Issue by jt7777777** [mifi/SimpleInstaBot#61]
Anybody has this problems as me? It started yesterday, bot always write this in application and if I try webview to do manual follow, button still did not change, I also tried it in ig app, but first when i clicked it did not change, after second attemp it changed but when i look at that account later it was same as before (not followed). I dont know if i have ban/ or made over limits, but when i had ban in past it always poped up some text about it. Also im using same setting as before. Could it be bug on ig site? 

<img width="912" alt="Snímka obrazovky 2021-04-02 o 13 57 52" src="https://user-images.githubusercontent.com/78236589/113413645-6d7ce080-93bb-11eb-8163-d29b9ee82b6d.png">

**Comment by mifi** [comment]
This probably means you are temp blocked. Try to open chrome developer tools and look for any error when you press the button

**Comment by jt7777777** [comment]
lol I made max threshold of followers, need to unfollow a lot of accounts, tnx for help
