### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by Filippinifra** [mifi/SimpleInstaBot#63]
I love your idea, your bot and your work.
I download it yesterday, this error occoured:

Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined
    at __puppeteer_evaluation_script__:1:61

node: 14.11.0
npm: 6.14.10

<img width="1076" alt="Screenshot 2021-04-16 at 00 49 51" src="https://user-images.githubusercontent.com/31794601/114947575-a900bb80-9e4d-11eb-80ec-d03592e4656d.png">

The bot start normally but then failed after navigate to profile page

**Comment by mifi** [comment]
dup #36
