### ISSUE TITLE
AssertionError: The expression evaluated to a falsy value

### ISSUE THREAD

**Issue by Unknownio** [mifi/SimpleInstaBot#71]
i tried to leaved default(10) but nothing works:

4:50 PMWaiting 2 sec
4:50 PMSetting language to English
4:50 PMWaiting 2 sec
4:50 PMWaiting 5 sec
4:50 PMSaving cookies
4:50 PMHave followed/unfollowed 0 in the last hour
4:50 PMHave followed/unfollowed 0 in the last 24 hours
4:50 PMHave liked 0 images in the last 24 hours
4:50 PMAssertionError: The expression evaluated to a falsy value:

  assert(ageInDays)
4:50 PMSleeping 6.969481698579694 hours (waiting until null

**Comment by mifi** [comment]
Oh, it seems you set "Automatically unfollow auto-followed users after this number of days" to 0. that's causing this issue. please set it to a valid number above 0
