### ISSUE TITLE
Running on Pi Zero W "Illegal instruction" terminal output on run (bot doesn't run on PI Zero!) 

### ISSUE THREAD

**Issue by birdman769** [mifi/SimpleInstaBot#81]
Hello, 

Thanks for this program. 

I first successfully got it running on a Raspberry pi 4. I thought it might be cool to see if it could run on a Pi Zero W. 

Identical installation as my Pi 4, but running "./simpleinstabot" , "sudo ./simpleinstabot" or the two run commands listed in the readme produces: 

"Illegal instruction"

in the terminal output. 

I'm wondering if you have any ideas on how to make it run or if this is just simply a limitation of the raspberry pi zero? 

Thanks again! 

EDIT: 

did some research and it would seem this error is produced by the ARM11 processor in the zero W being older and clashing with newer packages.

**Comment by mifi** [comment]
Yea, it seems like electron does not support armv6 (zero w). So nothing I can do about that unfortunately. See https://github.com/electron-userland/electron-builder/issues/2663 https://github.com/electron/electron/issues/9520
