### ISSUE TITLE
Unable to unfollow

### ISSUE THREAD

**Issue by yashshah** [mifi/SimpleInstaBot#86]
I have `dontUnfollowUntilDaysElapsed` set to 1 day which means it should unfollow all the users after 1 day but the script is always returning an empty array to unfollow.

Does the unfollow logic work as expected?

**Comment by mifi** [comment]
No it doesn't work like that. `dontUnfollowUntilDaysElapsed` only says how long it wait until it will try to unfollow users it has followed.

so it would do something like this:
- day 1:  follow 50 users, unfollow 0 users
- day 2:  follow 25 users, unfollow 25 users
- day 2:  follow 25 users, unfollow 25 users
- and so on...

**Comment by mifi** [comment]
i think not much i can do here. next version will include an unfollow only functionality fyi
