### ISSUE TITLE
Evaluation failed: TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by stefpriols** [mifi/SimpleInstaBot#87]
When I start the bot, I get this error:
`Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined
    at __puppeteer_evaluation_script__:1:61`

And then:
`Sleeping 13.816017582751709 hours (waiting until 10:00)...`

![Schermata 2021-08-26 alle 19 48 29](https://user-images.githubusercontent.com/24591510/131011790-c06611b8-56ce-4d32-9b58-c45b18494356.png)

**Comment by mifi** [comment]
this should now be fixed in next version
