### ISSUE TITLE
Headless Version for heroku?

### ISSUE THREAD

**Issue by itsOwen** [mifi/SimpleInstaBot#88]
can we get headless support so we can host it on heroku for free 24/7?

It's just a thought, Also the bot is super cool and fast

**Comment by mifi** [comment]
You can use https://github.com/mifi/instauto for headless automation (SimpleInstaBot is just a UI on top of that)

**Comment by itsOwen** [comment]
> You can use https://github.com/mifi/instauto for headless automation (SimpleInstaBot is just a UI on top of that)

thanks man ur the best
