### ISSUE TITLE
Program does not create a Log file

### ISSUE THREAD

**Issue by pateldhruv1993** [mifi/SimpleInstaBot#9]
I don't know if this is the expected behavior but the .exe file I downloaded from Releases tab does not create or log file or store any sort of data on my PC so that it can unfollow people that it has followed at a later date. 

I'm assuming it can only perform all the functions (un following, following new people after 24 hours etc) if you keep the program running 24/7. In that case I'd suggest allowing us an option to save the log file so the program can read that file on restart and restore its previous state

**Comment by mifi** [comment]
> I don't know if this is the expected behavior but the .exe file I downloaded from Releases tab does not create or log file or store any sort of data on my PC so that it can unfollow people that it has followed at a later date.

It does create a log in the appdata folder.



> I'm assuming it can only perform all the functions (un following, following new people after 24 hours etc) if you keep the program running 24/7. In that case I'd suggest allowing us an option to save the log file so the program can read that file on restart and restore its previous state

That's correct. It should already restore state if reopened
