### ISSUE TITLE
Save Login data

### ISSUE THREAD

**Issue by Sven9719** [mifi/SimpleInstaBot#92]
After login you are asked if you want to save the login data, the bot does not recognize this and then only says that the account is not logged in.

**Comment by mifi** [comment]
Could you provide a HTML dump?

Using the Web Inspector (F12) in the instagram browser window, go to the Elements tab, right click on the HTML tag and select Copy->Copy outerHTML. Then paste that here

**Comment by drogba72** [comment]
<div class="pV7Qt         DPiy6   qF0y9          Igw0E     IwRSH      eGOV_         _4EzTm                                                                                                               qhGB0 ZUqME"><div class="            qF0y9          Igw0E     IwRSH      eGOV_         _4EzTm      MGdpg                                                      aGBdT                                                  "><section class="ABCxa"><div class="JErX0"><div class="ig3mj"><div><span class="coreSpriteKeyhole"></span></div></div><div class="olLwo">Enregistrer vos identifiants&nbsp;?</div><div class="f5C5x">Nous pouvons enregistrer vos identifiants sur ce navigateur pour que vous n’ayez pas besoin de les entrer à nouveau.</div><button class="sqdOP  L3NKy   y3zKF     " type="button">Enregistrer les identifiants</button></div></section><div class="cmbtv"><button class="sqdOP yWX7d    y3zKF     " type="button">Plus tard</button></div></div></div>

**Comment by drogba72** [comment]
> Could you provide a HTML dump?
> 
> Using the Web Inspector (F12) in the instagram browser window, go to the Elements tab, right click on the HTML tag and select Copy->Copy outerHTML. Then paste that here

`For helping ;)

<div class="pV7Qt         DPiy6   qF0y9          Igw0E     IwRSH      eGOV_         _4EzTm                                                                                                               qhGB0 ZUqME"><div class="            qF0y9          Igw0E     IwRSH      eGOV_         _4EzTm      MGdpg                                                      aGBdT                                                  "><section class="ABCxa"><div class="JErX0"><div class="ig3mj"><div><span class="coreSpriteKeyhole"></span></div></div><div class="olLwo">Enregistrer vos identifiants&nbsp;?</div><div class="f5C5x">Nous pouvons enregistrer vos identifiants sur ce navigateur pour que vous n’ayez pas besoin de les entrer à nouveau.</div><button class="sqdOP  L3NKy   y3zKF     " type="button">Enregistrer les identifiants</button></div></section><div class="cmbtv"><button class="sqdOP yWX7d    y3zKF     " type="button">Plus tard</button></div></div></div>`

**Comment by mifi** [comment]
that link doesn't work. can you attach the html inside a .txt file here on github?

**Comment by drogba72** [comment]
With this, I think I'll be OK

https://www.casimages.com/f/cTVJZBYCFWb

**Comment by drogba72** [comment]
Yes it works !!
You're the BOSS ;)

Thanks

**Comment by drogba72** [comment]
I know ... It's not the same problem but I have this error 

Failed to process follower slama._.sa Error: Navigate to user returned status 560

**Comment by mifi** [comment]
Hopefully fixed in newest version
