### ISSUE TITLE
Says "Login has not succeeded" even though it worked - but does not go on

### ISSUE THREAD

**Issue by PaulinaJalou** [mifi/SimpleInstaBot#96]
![SimpleInstaBot](https://user-images.githubusercontent.com/75621182/140605097-e5fc146f-f9fe-4407-9164-edf3f758f009.png)

When I start the bot, it sets the language to English and enters the login data and the login works. However, it says that it´s not able to find the login page and the login does not work. After that I hang on a permanent waiting queue ... what could be the reason?

**Comment by mifi** [comment]
I think the page you are seeing with these suggestions is preventing the bot from knowing that it succeeded to log in. Could you try to
- click Cancel, or Next or similar on this dialog
- Click the Instagram logo in the top left to go to the home page

see if the bot can recover if you do any of those?

**Comment by mifi** [comment]
I think the page it navigated to is this: https://www.instagram.com/explore/people/
